# Generated by Django 5.2.8 on 2026-03-16 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CraftOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "craft_type",
                    models.CharField(
                        choices=[
                            ("fabrication", "Fabrication"),
                            ("upgrade", "Upgrade"),
                            ("pharma", "Pharmaceutical"),
                        ],
                        default="fabrication",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("item_type", models.CharField(max_length=20)),
                ("item_name", models.CharField(max_length=255)),
                ("item_category", models.CharField(blank=True, max_length=100)),
                ("item_data", models.JSONField(default=dict)),
                ("materials_cost", models.PositiveIntegerField(default=0)),
                (
                    "price_category",
                    models.CharField(default="Cheap/Everyday", max_length=30),
                ),
                ("dv", models.PositiveIntegerField(default=9)),
                ("time_hours", models.PositiveIntegerField(default=1)),
                ("tech_skill", models.CharField(default="basic_tech", max_length=50)),
                ("specialty_rank", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("roll_result", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(blank=True, null=True)),
                (
                    "crafter",
                    models.ForeignKey(
                        help_text="Character (Tech/MedTech) doing the crafting",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maker_craft_orders",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maker_craft_recipient",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Voucher created on success",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maker_craft_source",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["completed_at", "created_at"],
            },
        ),
    ]
