# Generated by Django 5.2.8 on 2026-03-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="craftorder",
            name="craft_type",
            field=models.CharField(
                choices=[
                    ("fabrication", "Fabrication"),
                    ("upgrade", "Upgrade"),
                    ("pharma", "Pharmaceutical"),
                    ("program", "Program"),
                    ("deckoption", "Deck Option"),
                ],
                default="fabrication",
                max_length=20,
            ),
        ),
    ]
