# Generated by Django 5.2.8 on 2026-03-09 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_board", "0002_faction_missions_gm_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="failure_penalty_scope",
            field=models.CharField(
                blank=True,
                choices=[("leader", "leader"), ("team", "team")],
                default="leader",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="missionteammember",
            name="added_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
