# Generated by Django 6.0.2 on 2026-03-10 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factions", "0002_faction_channel_id_faction_faction_head_and_more"),
        ("mission_board", "0003_alter_mission_failure_penalty_scope_and_more"),
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorySeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("max_budget", models.IntegerField(default=0)),
                ("voucher_rewards", models.JSONField(default=list)),
                ("item_rewards", models.JSONField(default=list)),
                ("rep_amount", models.IntegerField(default=0)),
                ("faction_rep_amount", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("claimed", "Claimed")],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_story_seeds",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_story_seeds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Faction the faction_rep_amount applies to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="story_seeds",
                        to="factions.faction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mission",
            name="source_seed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missions",
                to="mission_board.storyseed",
            ),
        ),
    ]
