# Generated by Django 6.0.2 on 2026-03-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=255)),
                ("recipients", models.CharField(max_length=1024)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
                ("read_by", models.CharField(default="", max_length=1024)),
                (
                    "character_recipients",
                    models.ManyToManyField(
                        blank=True, related_name="received_mail", to="objects.objectdb"
                    ),
                ),
                (
                    "read_by_characters",
                    models.ManyToManyField(
                        blank=True, related_name="read_mail", to="objects.objectdb"
                    ),
                ),
            ],
        ),
    ]
