# Generated by Django 4.2.15 on 2024-09-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=255)),
                ("recipients", models.CharField(max_length=1024)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
                ("read_by", models.CharField(default="", max_length=1024)),
            ],
        ),
    ]
