# Generated by Django 4.2.20 on 2025-05-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cyberware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("cost", models.IntegerField()),
                ("humanity_loss", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
                ("slots", models.IntegerField(default=1)),
                ("is_weapon", models.BooleanField(default=False)),
                ("damage_dice", models.IntegerField(default=0)),
                ("damage_die_type", models.IntegerField(default=6)),
                ("rate_of_fire", models.IntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
