# Generated by Django 6.0.2 on 2026-03-06 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cyberpunk_sheets", "0001_initial"),
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cyberware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("cost", models.IntegerField()),
                ("humanity_loss", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
                ("slots", models.IntegerField(default=1)),
                ("is_weapon", models.BooleanField(default=False)),
                ("damage_dice", models.IntegerField(default=0)),
                ("damage_die_type", models.IntegerField(default=6)),
                ("rate_of_fire", models.IntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CyberwareInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installed", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                (
                    "character_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cyberware_instances",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cyberware_instances_old",
                        to="cyberpunk_sheets.charactersheet",
                    ),
                ),
                (
                    "cyberware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cyberware_app_instances",
                        to="cyberware.cyberware",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("character_object__isnull", False),
                            ("character_sheet__isnull", False),
                            _connector="OR",
                        ),
                        name="cyberware_app_instance_has_character",
                    )
                ],
            },
        ),
    ]
