# Generated by Django 4.2.20 on 2025-05-02 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0001_initial"),
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
        ("cyberware", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CyberwareInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installed", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                (
                    "character_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cyberware_instances",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cyberware_instances_old",
                        to="cyberpunk_sheets.charactersheet",
                    ),
                ),
                (
                    "cyberware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cyberware_app_instances",
                        to="cyberware.cyberware",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cyberwareinstance",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("character_object__isnull", False),
                    ("character_sheet__isnull", False),
                    _connector="OR",
                ),
                name="cyberware_app_instance_has_character",
            ),
        ),
    ]
