# Generated by Django 4.2.15 on 2024-09-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberware", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyberware",
            name="requirements",
            field=models.TextField(blank=True),
        ),
    ]
