# Generated by Django 4.2.15 on 2024-09-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberware", "0003_alter_cyberware_requirements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cyberware",
            name="requirements",
        ),
        migrations.AddField(
            model_name="cyberware",
            name="damage_dice",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cyberware",
            name="damage_die_type",
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name="cyberware",
            name="is_weapon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cyberware",
            name="rate_of_fire",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="cyberware",
            name="cost",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cyberware",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="cyberware",
            name="humanity_loss",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cyberware",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
