# Generated by Django 4.2.15 on 2024-09-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_cyberwareinstance_is_cyberdeck_gear_is_cyberdeck"),
        ("netrunning", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cyberdeck",
            name="is_cyberware",
        ),
        migrations.AddField(
            model_name="cyberdeck",
            name="cyberware",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cyberdeck",
                to="inventory.cyberwareinstance",
            ),
        ),
        migrations.AddField(
            model_name="cyberdeck",
            name="gear",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cyberdeck",
                to="inventory.gear",
            ),
        ),
    ]
