# Generated by Django 6.0.2 on 2026-03-10 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0003_charactersheet_notoriety_and_more"),
        ("inventory", "0003_weaponattachment_weapon_attachment_slots_and_more"),
        ("netrunning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cyberdeck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("hardware_slots", models.IntegerField(default=0)),
                ("program_slots", models.IntegerField(default=0)),
                ("any_slots", models.IntegerField(default=0)),
                ("value", models.IntegerField(default=0)),
                (
                    "cyberdeck_gear",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cyberdeck",
                        to="inventory.cyberdeck",
                    ),
                ),
                (
                    "cyberware",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cyberdeck",
                        to="inventory.cyberwareinstance",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cyberdecks",
                        to="cyberpunk_sheets.charactersheet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="NetrunnerDeck",
        ),
    ]
