# Generated by Django 4.2.15 on 2024-09-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "netrunning",
            "0002_remove_cyberdeck_is_cyberware_cyberdeck_cyberware_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="cyberdeck",
        ),
        migrations.RemoveField(
            model_name="program",
            name="description",
        ),
        migrations.RemoveField(
            model_name="program",
            name="level",
        ),
        migrations.RemoveField(
            model_name="program",
            name="name",
        ),
    ]
