# Generated by Django 4.2.15 on 2024-09-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_cyberdeck"),
        (
            "netrunning",
            "0004_program_atk_program_cost_program_dfv_program_effect_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Hardware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("cost", models.IntegerField(default=0)),
                ("slots", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerICE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("per", models.IntegerField(default=0)),
                ("spd", models.IntegerField(default=0)),
                ("atk", models.IntegerField(default=0)),
                ("dfv", models.IntegerField(default=0)),
                ("rez", models.IntegerField(default=0)),
                ("effect", models.TextField(blank=True, default="")),
                ("cost", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="cyberdeck",
            name="gear",
        ),
        migrations.RemoveField(
            model_name="cyberdeck",
            name="max_programs",
        ),
        migrations.RemoveField(
            model_name="cyberdeck",
            name="slots",
        ),
        migrations.AddField(
            model_name="cyberdeck",
            name="any_slots",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cyberdeck",
            name="cyberdeck_gear",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cyberdeck",
                to="inventory.cyberdeck",
            ),
        ),
        migrations.AddField(
            model_name="cyberdeck",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cyberdeck",
            name="hardware_slots",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cyberdeck",
            name="program_slots",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cyberdeck",
            name="value",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cyberdeck",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
