# Generated by Django 4.2.15 on 2024-10-01 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0039_alter_charactersheet_unique_together"),
        ("inventory", "0015_alter_ammunition_ammo_type_alter_weapon_ammo_type"),
        ("netrunning", "0005_hardware_playerice_remove_cyberdeck_gear_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardware",
            name="cyberdeck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hardware",
                to="netrunning.cyberdeck",
            ),
        ),
        migrations.AddField(
            model_name="playerice",
            name="cyberdeck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_ice",
                to="netrunning.cyberdeck",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="cyberdeck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="netrunning.cyberdeck",
            ),
        ),
        migrations.AlterField(
            model_name="cyberdeck",
            name="cyberdeck_gear",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="netrunning_cyberdeck",
                to="inventory.cyberdeck",
            ),
        ),
        migrations.AlterField(
            model_name="cyberdeck",
            name="cyberware",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="netrunning_cyberdeck",
                to="inventory.cyberwareinstance",
            ),
        ),
        migrations.AlterField(
            model_name="cyberdeck",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_cyberdecks",
                to="cyberpunk_sheets.charactersheet",
            ),
        ),
        migrations.AlterField(
            model_name="netrunsession",
            name="architecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="netrunning.netarchitecture",
            ),
        ),
        migrations.AlterField(
            model_name="netrunsession",
            name="current_node",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_sessions",
                to="netrunning.node",
            ),
        ),
    ]
