# Generated by Django 4.2.20 on 2025-05-02 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0016_character"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("payout", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="NEW",
                        max_length=10,
                    ),
                ),
                ("claimed", models.BooleanField(default=False)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MODERATE", "Moderate"),
                            ("HIGH", "High"),
                            ("EXTREME", "Extreme"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("genre", models.CharField(max_length=30)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("next_session", models.DateTimeField(blank=True, null=True)),
                (
                    "participants",
                    models.ManyToManyField(related_name="plots", to="objects.objectdb"),
                ),
                (
                    "storyteller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_storytellers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("duration", models.DurationField()),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("secrets", models.TextField()),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="sessions", to="objects.objectdb"
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="plots.plot",
                    ),
                ),
            ],
        ),
    ]
