# Generated by Django 6.0.2 on 2026-03-10 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elflines", "0001_initial"),
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elfline",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="In-fiction name with brackets e.g. {nature's_thorns}",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="elfline",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="elflinemembership",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="elflinesheet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="elflinesheet",
            name="is_complete",
            field=models.BooleanField(
                default=False,
                help_text="Sheet has been finalized (50 STAT, 60 skill pts spent, elfname set).",
            ),
        ),
        migrations.AlterField(
            model_name="elflinesheet",
            name="last_camp_room",
            field=models.ForeignKey(
                blank=True,
                help_text="Teleport here on death.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="objects.objectdb",
            ),
        ),
        migrations.AlterField(
            model_name="elflinesheet",
            name="revive_sickness",
            field=models.BooleanField(
                default=False, help_text="MOVE 1 until 2000gp paid to remove."
            ),
        ),
        migrations.AlterField(
            model_name="elflinesheet",
            name="stat_increases_by_rank",
            field=models.JSONField(
                default=list,
                help_text="STATs increased at ranks 1-3: ['reflexes','dex','body']",
            ),
        ),
    ]
