# Generated by Django 4.2.20 on 2025-05-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HangoutDB",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.objectdb",),
        ),
    ]
