# Generated by Django 4.2.15 on 2024-09-16 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0016_charactersheet_handle"),
        ("factions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="cyberpunk_sheets.charactersheet",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="factions.group",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "group")},
            },
        ),
    ]
