# Generated by Django 4.2.20 on 2025-05-03 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0016_character"),
        ("factions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faction",
            name="coleader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="co_led_factions",
                to="objects.objectdb",
            ),
        ),
        migrations.AddField(
            model_name="faction",
            name="faction_type",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="faction",
            name="leader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_factions",
                to="objects.objectdb",
            ),
        ),
    ]
