# Generated by Django 6.0.2 on 2026-03-09 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factions", "0001_initial"),
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="faction",
            name="channel_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faction",
            name="faction_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_factions",
                to="objects.objectdb",
            ),
        ),
        migrations.AddField(
            model_name="faction",
            name="members_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="faction",
            name="staff_sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sponsored_factions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="factionreputation",
            name="notoriety",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="factionreputation",
            name="notoriety_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="factionreputation",
            name="rep",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="factionreputation",
            name="reputation_points",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="FactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon"),
                            ("armor", "Armor"),
                            ("gear", "Gear"),
                            ("cyberware", "Cyberware"),
                            ("vehicle", "Vehicle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "item_key",
                    models.CharField(
                        help_text="Key/name in equipment_data or cyberware_data",
                        max_length=255,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                (
                    "price",
                    models.IntegerField(default=0, help_text="Price in eurodollars"),
                ),
                ("voucher_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faction_items",
                        to="factions.faction",
                    ),
                ),
            ],
            options={
                "unique_together": {("faction", "item_type", "item_key")},
            },
        ),
    ]
