# Generated by Django 4.2.15 on 2024-09-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factions", "0003_groupinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupinfo",
            options={"verbose_name": "Group Info", "verbose_name_plural": "Group Data"},
        ),
        migrations.AddField(
            model_name="faction",
            name="ic_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="group",
            name="ic_description",
            field=models.TextField(blank=True),
        ),
    ]
