# Generated by Django 4.2.15 on 2024-10-01 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0039_alter_charactersheet_unique_together"),
        ("factions", "0004_alter_groupinfo_options_faction_ic_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmembership",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_memberships",
                to="cyberpunk_sheets.charactersheet",
            ),
        ),
    ]
