# Generated by Django 4.2.15 on 2024-10-01 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0039_alter_charactersheet_unique_together"),
        ("factions", "0005_alter_groupmembership_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factionreputation",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faction_reputations",
                to="cyberpunk_sheets.charactersheet",
            ),
        ),
    ]
