# world/cyberware/cyberware_data.py

from .models import Cyberware
from world.list_data import SKILL_TO_STAT
"""
The dictionary data utilizes the following pattern for an entry:

    {
        "name": "",
        "type": "",
        "slots": ,
        "humanity_loss": ,
        "cost": ,
        "description": " "
    },

    """

CYBERWARE_DATA_LIST = [
    # Fashionware
    {
        "name": "Biomonitor",
        "type": "Fashionware",
        "slots": 1,
        "humanity_loss": 0,
        "cost": 100,
        "is_weapon": False,
        "description": "Subdermal implant which generates a constant LED readout of pulse, temperature, respiration, blood sugar, etc. You can link your Biomonitor to your Agent to allow it to track your wellness."
    },
    {
        "name": "Chemskin",
        "type": "Fashionware",
        "slots": 1,
        "humanity_loss": 0,
        "cost": 100,
        "is_weapon": False,
        "description": "Dyes and pigments infused into the skin to permanently change its hue."
    },
    {
        "name": "EMP Threading",
        "type": "Fashionware",
        "slots": 1,
        "humanity_loss": 0,
        "cost": 10,
        "is_weapon": False,
        "description": "Thin silver lines that run in circuit-like patterns across the body."
    },
    {
        "name": "Light Tattoo",
        "type": "Fashionware",
        "slots": 1,
        "humanity_loss": 0,
        "cost": 100,
        "is_weapon": False,
        "description": "Subdermal patches store light and project colored tattoos under the skin. +2 to Style if the user has three or more tattoos."
    },
    {
        "name": "Shift Tacts",
        "type": "Fashionware",
        "slots": 1,
        "humanity_loss": 0,
        "cost": 100,
        "is_weapon": False,
        "description": "Color-changing lenses implanted into the eye itself!"
    },
    {
        "name": "Skinwatch",
        "type": "Fashionware",
        "slots": 1,
        "humanity_loss": 0,
        "cost": 100,
        "is_weapon": False,
        "description": "Subdermally implanted LED watch."
    },
    {
        "name": "Techhair",
        "type": "Fashionware",
        "slots": 1,
        "humanity_loss": 0,
        "cost": 100,
        "is_weapon": False,
        "description": "Color-light-emitting artificial hair."
    },
    # Black Chrome Fashionware
    {
        "name": "Heuristic Health Monitor",
        "type": "Fashionware",
        "slots": 0,
        "humanity_loss": 0,
        "cost": 500,
        "is_weapon": False,
        "description": "Requires Biomonitor. Sensors track tissue health, bone density, muscle gains. Displays Healthy Persons (HP) heuristic. User knows their own Hit Points at a glance.",
        "requirements": "Biomonitor",
    },
    # Add more Fashionware items -- Leaving open in case of new book releases.

    # Neuralware
    {
        "name": "Neural Link",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Wired artificial nervous system. Required to use Neuralware and Subdermal Grip. System has 5 Option Slots for Neuralware Options."
    },
    {
        "name": "Kerenzikov",
        "type": "Neuralware",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 500,
        "is_weapon": False,
        "description": "Speedware. User adds +2 to Initiative. Only 1 piece of Speedware can be installed at a time."
    },
    {
        "name": "Braindance Recorder",
        "type": "Neuralware",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Records user's experiences to memory chip or external device. Requires Neural Link or Neuroport.",
        "requirements": "Neural Link or Neuroport",
    },
    {
        "name": "Chipware Socket",
        "type": "Neuralware",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "A single socket installed in the back of the neck that allows quick installation of a single piece of Chipware, of which there are many varieties. Installing or uninstalling a single piece of Chipware from a Chipware Socket is an Action. The first time you install a piece of Chipware you've never used before, you always accrue Humanity Loss. Re-installing Chipware you've already used doesn't do this. Chipware does not take up a Neural Link Option Slot. Multiple sockets may be installed, but each must be paid for individually. Requires Neural Link or Neuroport.",
        "requirements": "Neural Link or Neuroport",
    },
    {
        "name": "Interface Plugs",
        "type": "Neuralware",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Plugs in wrist or head that allow connection to machines."
    },
    {
        "name": "Sandevistan",
        "type": "Neuralware",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Speedware. When activated as an Action adds +3 initiative for one minute. Has 1 hour cool down period. Only 1 piece of speedware can be installed at a time. Requires Neural Link.",
        "requirements": "Neural Link",
    },
    {
        "name": "Chemical Analyzer",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": False,
        "description": "Chipware. Tests substance for precise chemical composition and compares to a database. Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    },
    {
        "name": "Memory Chip",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 0,
        "cost": 10,
        "is_weapon": False,
        "description": "Chipware. The standard for data storage. While installed into a Chipware socket, the user's cyberware can store data on it or access data stored on it. Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    },
    {
        "name": "Olfactory Boost",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 100,
        "is_weapon": False,
        "description": "Chipware. While installed into a Chipware Socket, the user's sense of smell is boosted, allowing them to use the Tracking Skill to track scent in addition to visual clues. Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    },
    {
        "name": "Pain Editor",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "Chipware. While installed into a Chipware Socket, a Pain Editor shuts off the user's pain receptors dynamically, allowing them to ignore the effects of the Seriously Wounded Wound State. Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    },
    {
        "name": "Basic Skill Chip",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Chipware. While installed into a Chipware Socket, a Skill Chip makes the Skill it was made for trained for the user at +3, unless the user's Skill was already trained higher than +3, in which case it does nothing. Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    },
    {
        "name": "Advanced Skill Chip",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 1000,
        "is_weapon": False,
        "description": "Chipware. While installed into a Chipware Socket, a Skill Chip makes the Skill it was made for trained for the user at +3, unless the user's Skill was already trained higher than +3, in which case it does nothing. This is for any skill that is purchased at 2x (Pilot Air, Martial Arts, Autofire, Heavy Weapons, Demolitions, Electronics, or Paramedic) Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    },
    {
        "name": "Tactile Boost",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 100,
        "is_weapon": False,
        "description": "Chipware. While installed into a Chipware Socket, it boosts the user's sense of touch, allowing them to detect motion within 20m/yds of them, as long as their hand is touching a surface. While in use as a motion detector, that hand can't be used to do anything else. Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    },
    # Black Chrome Neuralware
    {
        "name": "Budget Chipware Socket",
        "type": "Neuralware",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 100,
        "is_weapon": False,
        "description": "Neuralware Option. Requires Neural Link. Single Chipware socket. Head damage ejects chip 30m; 1d10 on 1 destroys it.",
        "requirements": "Neural Link",
    },
    {
        "name": "Explicit Memory Stimulator",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "Chipware. +2 to Concentration Checks to remember information. Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    },
    {
        "name": "Reflex Co-Processor",
        "type": "Neuralware",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 500,
        "is_weapon": False,
        "description": "Neuralware Option. Assists Neural Link in processing, freeing it to focus on enhancing reflexes. User with Reflex Co-Processor can dodge bullets regardless of REF. Requires Neural Link.",
        "requirements": "Neural Link",
    },
    # Add more Neuralware items -- Leaving open in case of new book releases.

    # Cyberoptics
    {
        "name": "Cybereye",
        "type": "Cyberoptics",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 100,
        "is_weapon": False,
        "description": "All following options are installed in an artificial eye that replaces a meat one. Each Cybereye has 3 Option Slots for Cybereye Options. Some options must be paired to work properly (purchased twice and installed in two different Cybereyes on a user. Humanity Loss is calculated separately for each purchase)."
    },
    {
        "name": "Chyron",
        "type": "Cyberoptics",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "Projects a tiny subscreen into user's normal field of vision for messages, video, etc. from a user's other cyberware or electronics. Picture in a picture for real life. Requires a Cybereye.",
        "requirements": "Cybereye",
    },
    {
        "name": "Anti-Dazzle",
        "type": "Cyberoptics",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "Reduces penalties from bright lights and flash effects. Immune to flashbang blindness. Requires Cybereye.",
        "requirements": "Cybereye",
    },
    {
        "name": "Color Shift",
        "type": "Cyberoptics",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "Cosmetic upgrade allows unlimited color and pattern changes to be made as an Action. Eye can optionally be temperature sensitive or reactant to hormone changes in the body. Requires a Cybereye.",
        "requirements": "Cybereye",
    },
    {
        "name": "Dartgun",
        "type": "Cyberoptics",
        "slots": 3,
        "humanity_loss": 2,
        "cost": 500,
        "is_weapon": False,
        "description": "Dartgun Exotic Weapon, with only a single shot in the clip, concealed inside the Cybereye. Requires a Cybereye and takes 3 Option Slots.",
        "requirements": "Cybereye",
    },
    {
        "name": "Image Enhance",
        "type": "Cyberoptics",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": False,
        "description": "User adds +2 to their Perception, Lip Reading, and Conceal/Reveal Object Skills for Checks which include sight. Requires two Cybereyes and must be paired.",
        "requirements": "Cybereye",
    },
    {
        "name": "Low Light-IR-UV",
        "type": "Cyberoptics",
        "slots": 2,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": False,
        "description": "Reduces penalties imposed by darkness and other intangible obscurement, like smoke, fog, etc. to 0. User can distinguish hot meat from cold metal but cannot see through anything that could provide cover. Requires two Cybereyes, must be paired, and takes 2 Option Slots per Cybereye.",
        "requirements": "Cybereye",
    },
    {
        "name": "MicroOptics",
        "type": "Cyberoptics",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 500,
        "is_weapon": False,
        "description": "Cybereye option providing optical magnification for detailed viewing. Requires Cybereye.",
        "requirements": "Cybereye",
    },
    {
        "name": "MicroVideo",
        "type": "Cyberoptics",
        "slots": 2,
        "humanity_loss": 2,
        "cost": 500,
        "is_weapon": False,
        "description": "Camera in eye records video and audio to a standard Memory Chip or linked Agent. Requires a Cybereye and takes 2 option slots.",
        "requirements": "Cybereye",
    },
    {
        "name": "Radiation Detector",
        "type": "Cyberoptics",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 1000,
        "is_weapon": False,
        "description": "Radiation readings within 100m/yds of the user are displayed in user's vision hovering over their source in the form of a blue glow.  Requires a Cybereye.",
        "requirements": "Cybereye",
    },
    {
        "name": "Targeting Scope",
        "type": "Cyberoptics",
        "slots": 1,
        "humanity_loss": 4,
        "cost": 500,
        "is_weapon": False,
        "description": "User gets a +1 to their Check when making an Aimed Shot. Multiple installations of this option provide user no additional benefit. Requires a Cybereye.",
        "requirements": "Cybereye",
    },
    {
        "name": "TeleOptics",
        "type": "Cyberoptics",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": False,
        "description": "User can see detail up to 800m/yds away. When attacking a target 51m/yds or further away with either a weapon's single shot firing mode or an Aimed Shot, you can add a +1 to your Check. Multiple installations of this option provide user no additional benefit. Does not stack with Sniping Scope Weapon Attachment.  Requires a Cybereye.",
        "requirements": "Cybereye",
    },
    {
        "name": "Virtuality",
        "type": "Cyberoptics",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "Projects cyberspace imagery over user's view of the world. Never forget your Virtuality Goggles again. Requires two Cybereyes and must be paired.",
        "requirements": "Cybereye",
    },

    # Black Chrome Cyberoptics
    {
        "name": "Sponsored Cybereye",
        "type": "Cyberoptics",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 50,
        "is_weapon": False,
        "description": (
            "A full Cybereye implant (not a cosmetic cover): 2 Option Slots, preinstalled Chyron (cannot remove). "
            "Can pair with a second Sponsored or standard Cybereye, or install under a MultiOptic Mount like Cybereye. "
            "Up to 1/hr GM can serve ad: -1 to vision Checks until Action to close."
        ),
    },
    {
        "name": "Hardened Cybereye Casing",
        "type": "Cyberoptics",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": False,
        "description": (
            "You didn't dig out your eyeballs and install cyberoptics just to watch the world go dark "
            "because someone blasted off an EMP or hit you with a stray Microwaver pulse. "
            "Cybereye option: cybereye internals are hardened to military standards; the cybereye and "
            "installed options cannot be disabled, inoperable, or destroyed by electric shock, "
            "microwaver or EMP pulses, or any Non-Black ICE program effect."
        ),
        "requirements": "Cybereye or Sponsored Cybereye or Kiroshi MonoVision or Cyclops International Bug Eye",
    },
    # Add more Cyberoptics items -- Leaving open in case of new book releases.

    # Cyberaudio
    {
        "name": "Cyberaudio Suite",
        "type": "Cyberaudio",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Cyberaudio Suite is installed invisibly in the skull. System has 3 options for Cyberaudio Options. The user can only have one Cyberaudio Suite installed."
    },
    {
        "name": "Amplified Hearing",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "User adds +2 to their Perception Skill for Checks which include hearing. Requires a Cyberaudio Suite. Multiple installations of this option provide user no additional benefit.",
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "Audio Recorder",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "Records audio to a standard Memory Chip or a linked Agent. Requires a Cyberaudio Suite.",
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "Bug Detector",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": " Beeps when user is within 2m/yds of a tap, bug, or other listening device. Requires a Cyberaudio Suite.",
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "Homing Tracer",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "Can follow a linked tracer up to 1 mile away. Comes with a free button-sized linked tracer. Replacements are 50eb. Requires a Cyberaudio Suite.",
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "Internal Agent",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "Fully functional Agent, controlled entirely via voice commands. Images are described, but output can be linked to a Cybereye with Chyron or a nearby screen if visual output is desired. The implanted Agent's Memory Chip cannot be removed without surgery. Requires a Cyberaudio Suite.",
        "quality": "standard",
        "app_slots": 6,
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "EBM Pir2",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": False,
        "description": "EBM's version of the basic Internal Agent improves reliability without increasing the risk of migraines. Cyberaudio Option. Excellent Quality Internal Agent. Requires a Cyberaudio Suite.",
        "quality": "excellent",
        "app_slots": 8,
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "MediaWare Braingen",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 50,
        "is_weapon": False,
        "description": "A discount Agent, cheaply made but readily available. Rumors of security exploits allowing direct access to a user's brain are unsubstantiated and considered libelous by the company. Cyberaudio Option. Poor Quality Internal Agent. Requires a Cyberaudio Suite.",
        "quality": "poor",
        "app_slots": 4,
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "Raven Microcybernetics Drake",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "A common model of Internal Agent, with no stand-out features but no great weaknesses. Cyberaudio Option. Standard Quality Internal Agent. Requires a Cyberaudio Suite.",
        "quality": "standard",
        "app_slots": 6,
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "Rocklin Augmentics Neuron",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 1000,
        "is_weapon": False,
        "description": "A post-war design just hitting the market, Rocklin's Neuron uses revolutionary new technology to project video directly via the user's optic nerve, eliminating the need for cyberoptics. Cyberaudio Option. Excellent Quality Internal Agent. Displays visual output into user's field of vision even if they do not have Cybereyes with Chyron installed. Requires a Cyberaudio Suite.",
        "quality": "excellent",
        "app_slots": 8,
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "Level Damper",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "Automatic noise compensation. User is immune to deafness or other effects caused by dangerously loud noises, like those produced by a flashbang. Requires a Cyberaudio Suite.",
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "Radio Communicator",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "User can communicate via radio, 1-mile range. Cyberaudio Suite. Requires a Cyberaudio Suite",
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "Radio Scanner and Music Player",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 50,
        "is_weapon": False,
        "description": "User can use an Action to scan all radio bands within a mile that are currently being used and tune into them. Music player can link to the Data Pool to listen to the hottest music or play directly from a Memory Chip. Understanding scrambled channels requires a Scrambler/Descrambler. Requires a Cyberaudio Suite.",
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "Radar Detector",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 500,
        "is_weapon": False,
        "description": "Beeps if active radar beam is present within 100m/yds. Requires a Cyberaudio Suite",
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "Scrambler Descrambler",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "Allows user to scramble outgoing communications so they cannot be understood without a descrambler, which is also included at no extra charge. Requires a Cyberaudio Suite.",
        "requirements": "Cyberaudio Suite",
    },
    {
        "name": "Voice Stress Analyzer",
        "type": "Cyberaudio",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "User adds +2 to their Human Perception and Interrogation Skills. User can activate a special lie-detecting function for a minute with an Action, during which time the GM rolls all your Character's Human Perception and Interrogation Checks privately, beeping once whenever it detects a lie, or whenever they desire after a failed roll. Beware of false positives and negatives. Requires a Cyberaudio Suite.",
        "requirements": "Cyberaudio Suite",
    },


    # Black Chrome Cyberaudio
    {
        "name": "Discount Cyberaudio Suite",
        "type": "Cyberaudio",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "Cyberaudio Suite with large outer component. Only 1 Option Slot for Cyberaudio Options. User can only have one Cyberaudio Suite.",
    },
    # Add more Cyberaudio items -- Leaving open in case of new book releases.


    # Internal Cyberware
    {
        "name": "AudioVox",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": False,
        "description": "Vocal synthesizer. User adds +2 to their Acting skill and also adds +2 to their Play Instrument Skill while singing. Multiple installations of this option provide user no additional benefit."
    },
    {
        "name": "Contraceptive Implant",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 0,
        "cost": 10,
        "is_weapon": False,
        "description": "Implant prevents undesired pregnancy regardless of equipment."
    },
    {
        "name": "Enhanced Antibodies",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 500,
        "is_weapon": False,
        "description": "After stabilization, the user heals a number of Hit Points equal to twice their BODY for each day they spend resting, doing only light activity, and spending the majority of the day taking it easy until returning to full HP, instead of at their typical rate."
    },
    {
        "name": "Cybersnake",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": True,
        "damage_dice": 4,
        "damage_die_type": 6,
        "rate_of_fire": 1,
        "description": "Horrifying throat/esophagus-mounted tentacle weapon. A Very Heavy Melee Weapon (4d6, 1 ROF) that can be successfully concealed without a Check."
    },
    {
        "name": "Gills",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 1000,
        "is_weapon": False,
        "description": "User can breathe underwater."
    },
    {
        "name": "Grafted Muscle and Bone Lace",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "User increases their Body by 2. This increase in Body changes a Character's HP, Wound Threshhold, and Death Save. Multiple installments stack. Cannot raise Body above 10."
    },
    {
        "name": "Independent Air Supply",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 1000,
        "is_weapon": False,
        "description": "Contains 30 minutes of air, before the user needs to refill the tank from the ambient air, which takes an hour. Alternatively, replacing an empty tank with a full one (50eb), takes an Action."
    },
    {
        "name": "Midnight Lady Sexual Implant",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 100,
        "is_weapon": False,
        "description": "Be a Venus, be the fire. Be desire."
    },
    {
        "name": "Mr. Studd Sexual Implant",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 100,
        "is_weapon": False,
        "description": "All night, every night. And they'll never know."
    },
    {
        "name": "Nasal Filters",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "User is immune to the effects of toxic gasses, fumes, and all similar dangers that must be inhaled to affect the user. User can deactivate nasal filters, if desired, without an Action."
    },
    {
        "name": "Radar Sonar Implant",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 1000,
        "is_weapon": False,
        "description": "Constantly scans terrain within 50m/yds of user, including underwater, for new threats. Scan does not include anything behind cover, like the contents of a room behind a closed door. User receives a beep from the GM along with the direction of its source whenever a new moving object is detected on the scan."
    },
    {
        "name": "Toxin Binders",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "User adds +2 to their Resist Torture/Drugs Skill. Multiple installations of this option provide user no additional benefit."
    },
    {
        "name": "Vampyres",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 500,
        "is_weapon": True,
        "damage_dice": 1,
        "damage_die_type": 6,
        "rate_of_fire": 2,
        "description": "Fangs implanted in the user's mouth. An Excellent Quality Light Melee Weapon (1d6 damage, 2 ROF) that can be successfully concealed without a Check. A Vial of Poison or Biotoxin (see gear) can be safely stored and concealed in a compartment in the roof of the mouth near the fangs without a Check. The contents of the stored vial can then be applied to the Vampyres silently anytime without an Action. Each application uses an entire vial and lasts for 30 minutes. Installation of Vampyres includes a complete rework of the user's mouth which prevents the possibility of poisoning yourself accidentally with your fangs halfway through a slice of pizza or due to a bad Check." 
    },
    # Black Chrome Internal Body
    {
        "name": "RacerBracer",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Cervical spine upgrade. Immune to Whiplash Critical Injury.",
    },
    {
        "name": "Trauma Response Nanomatrix",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 1000,
        "is_weapon": False,
        "description": "Once per day as Action: repair Skin Weave or Subdermal Armor to full SP. Requires Skin Weave or Subdermal Armor. Additional installs +1 use/day.",
        "requirements": "Skin Weave or Subdermal Armor",
    },
    {
        "name": "Internal Body Cyberware Hardened Shielding",
        "type": "Internal Body",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "All Internal Body cyberware immune to electric shock, microwaver, EMP, Non-Black ICE program effects.",
    },
    {
        "name": "Quick Change Faceplate Mount",
        "type": "Internal Body",
        "slots": 0,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "Replaces meat face with mounting for Faceplates. Faceplate install/uninstall: Action. Purchase includes 1 personalized Faceplate. Additional Faceplates (Realskinn/SuperChrome) 100eb. Install: Hospital.",
    },
    {
        "name": "Sycust Cyberspine",
        "type": "Internal Body",
        "slots": 3,
        "humanity_loss": 7,
        "cost": 1000,
        "is_weapon": False,
        "description": "Immune to Spinal Injury Critical Injury and bonus damage. Hardened: immune to EMP, Microwaver, Non-Black ICE Program effects. +1 to Contortionist Checks. Counts as orifice for Cybersnake mount. Install: Hospital.",
    },
    # Add more Internal Cyberware items -- Leaving open in case of new book releases.


    # External Cyberware
    {
        "name": "Hidden Holster",
        "type": "External Body",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Holster inside the user's body can store a weapon already capable of concealment so that it can be successfully concealed without a roll. Weapon can be drawn from the hidden holster without an Action, as long as it is implanted in an easily accessible place on the user's body. You don't want one in your thigh unless you don't wear pants."
    },
    {
        "name": "Skin Weave",
        "type": "External Body",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "User's body and head are armored at SP7. Your SP in any location is determined by your highest source of SP in that location. Additionally, whenever your armor is ablated in a location, all your sources of SP in that location are ablated at the same time. Whenever the user successfully completes a day of natural healing, nanomachines present in the Skin Weave repair both the body and head location of the Skin Weave for one point of its lost SP."
    },
    {
        "name": "Subdermal Armor",
        "type": "External Body",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "User's body and head are armored at SP11. Your SP in any location is determined by your highest source of SP in that location. Additionally, whenever your armor is ablated in a location, all your sources of SP in that location are ablated at the same time. Whenever the user successfully completes a day of natural healing, nanomachines present in the Subdermal Armor repair both the body and head location of the Subdermal Armor for one point of its lost SP."
    },
    {
        "name": "Subdermal Pocket",
        "type": "External Body",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "2x4 (5cm x 10cm) space with a Realskinn zipper. Contents can be successfully concealed without a Check."
    },

    # Add more External Cyberware items -- Leaving open in case of new book releases.

    # Cyberlimbs
    {
        "name": "Cyberarm",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Replacement arm. Does not have to be paired. A Cyberarm has 4 Option Slots for Cyberarm or Cyberlimb Options, and each comes pre-installed with a Standard Hand that doesn't cost any Humanity Loss or take up a Cyberarm Option Slot."
    },
    {
        "name": "Standard Hand",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 2,
        "cost": 100,
        "description": "Resembles a normal hand. If installed into a meat arm, a standard hand doesn't count towards the number of pieces of cyberware installed in a meat arm. Doesn't take up a Cyberarm Option Slot."
    },
    {
        "name": "Big Knucks",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": True,
        "damage_dice": 2,
        "damage_die_type": 6,
        "rate_of_fire": 2,
        "description": "Armored knuckles. A Medium Melee Weapon (2d6 damage, 2 ROF) that can be successfully concealed without a Check. When wielded as a weapon, user can't hold anything in this arm's hand. Can be installed as the only piece of Cyberware in a meat arm."
    },
    {
        "name": "Cyberdeck",
        "type": "Cyberarm",
        "slots": 3,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": False,
        "description": "Cyberdeck permanently installed into the user's Cyberarm. A Cyberdeck must be provided by the user at the time of installation. In addition to never accidentally misplacing your Cyberdeck, integration into a Cyberarm gives any Cyberdeck 1 extra slot that can be used for either Programs or Hardware. This is a permanent upgrade. Attempting to uninstall the Cyberdeck from the Cyberarm breaks it beyond repair, but any Programs or Hardware on it could be easily recovered. Requires a Cyberarm and takes 3 Option Slots. Cyberdeck still requires Interface Plugs and Neural Link to be operated by the user.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Grapple Hand",
        "type": "Cyberarm",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "User, as an Action, can fire a rocket propelled grapple that will attach securely to any Thick cover up to 30m/yds away. Line can only support two times the user's body weight, and has 10 HP. The user negates the normal movement penalty for climbing when they climb this line, and can retract the line without an Action, including as they climb. When used as a grapple, user can't hold anything in this arm's hand. Ineffective as a weapon and cannot be used to make the Grab Action. Requires a Cyberarm.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Medscanner",
        "type": "Cyberarm",
        "slots": 2,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Scanner with external probes and contacts diagnoses injury and illness, assisting user in medical emergencies not requiring the Surgery Skill. User adds +2 to their First Aid and Paramedic Skills. Requires a Cyberarm and takes 2 Option Slots. Multiple installations of this option provide user no additional benefit.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Popup Grenade Launcher",
        "type": "Cyberarm",
        "slots": 2,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "A One-Handed Grenade Launcher with only a single grenade in its magazine that is incompatible with all Weapon Attachments except Smartgun Link is installed into the Cyberarm. Launcher can be successfully concealed without a Check and can be drawn and stowed without an Action. While the weapon is 'popped up,' the user can't hold anything in this arm's hand. Requires a Cyberarm and takes 2 Option Slots.",
        "requirements": "Cyberarm"
    },
    {
        "name": "Popup Melee Weapon",
        "type": "Cyberarm",
        "slots": 2,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "A One-Handed Light, Medium, or Heavy Melee Weapon (that need not be concealable before its installation) is installed in a Cyberarm so that it can be successfully concealed without a roll, and can be drawn and stowed without an Action. While the weapon is 'popped up,' the user can't hold anything in this arm's hand. Requires a Cyberarm and takes 2 Option Slots.",
        "requirements": "Cyberarm"
    },
    {
        "name": "Popup Shield",
        "type": "Cyberarm",
        "slots": 3,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "A Bulletproof Shield which is concealed while it is folded inside the Cyberarm. It can be drawn or stowed without an Action, provided that the shield has more than 0 HP. When extended, you can't use the Cyberarm to do anything else other than serve as a shield, and you can't hold anything in that Cyberarm's hand other than the shield. The Bulletproof Shield installed inside your Cyberarm is easily removable and replaceable with another Bulletproof Shield, for ease of cleaning and repair. Requires a Cyberarm and takes 3 Option Slots.",
        "requirements": "Cyberarm"
    },
    {
        "name": "Popup Ranged Weapon",
        "type": "Cyberarm",
        "slots": 2,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": " A One-Handed Ranged Weapon (that need not be concealable before its installation) provided by the user is permanently installed into the Cyberarm (along with any weapon attachments attached to it) so that it can be successfully concealed without a Check, and can be drawn and stowed without an Action. While the weapon is \"popped up,\" the user can't hold anything in this arm's hand. Requires a Cyberarm and takes 2 Option Slots.",
        "requirements": "Cyberarm"

    },
    {
        "name": "Quick Change Mount",
        "type": "Cyberarm",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 100,
        "is_weapon": False,
        "description": "Cyberarm can be installed in an open socket or uninstalled with an Action. The first time you install a brand new Cyberarm, whether using a Quick Change Mount or otherwise, you always accrue Humanity Loss. Reattaching one you've already used before with a Quick Change Mount does not do this. Requires a Cyberarm.",
        "requirements": "Cyberarm"
    },
    {
        "name": "Rippers",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": True,
        "damage_dice": 2,
        "damage_die_type": 6,
        "rate_of_fire": 2,
        "description": "Extendable Carbo-glass fingernails. A Medium Melee Weapon (2d6 damage, 2 ROF) that can be successfully concealed without a Check. When wielded as a weapon, user can't hold anything in this arm's hand. Can be installed as the only piece of Cyberware in a meat arm."
    },
    {
        "name": "Scratchers",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": True,
        "damage_dice": 1,
        "damage_die_type": 6,
        "rate_of_fire": 2,
        "description": "Carbo-glass artificial fingernails that cut on a diagonal slice. A Light Melee Weapon (1d6 damage, 2 ROF) that can be successfully concealed without a Check. When wielded as a weapon, user can't hold anything in this arm's hand. Can be installed as the only piece of Cyberware in a meat arm."
    },
    {
        "name": "Shoulder Cam",
        "type": "Cyberarm",
        "slots": 2,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Camera in a popup in the user's shoulder that tracks independently of the user and records video and audio to an onboard Memory Chip or a linked Agent. Camera can be successfully concealed without a Check and can be drawn and stowed without an Action. Requires a Cyberarm and takes 2 Option Slots.",
        "requirements": "Cyberarm"
    },
    {
        "name": "Slice N Dice",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": True,
        "damage_dice": 2,
        "damage_die_type": 6,
        "rate_of_fire": 2,
        "description": "Monofilament whip implanted in the user's thumb. A Medium Melee Weapon (2d6 damage, 2 ROF) that can be successfully concealed without a Check. When wielded as a weapon, user can't hold anything in this arm's hand. Can be installed as the only piece of Cyberware in a meat arm."
    },
    {
        "name": "Rocklin Augmentics Quick Digits",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 250,
        "is_weapon": False,
        "description": "Cyberhand. Can be installed as the only piece of cyberware in a meat arm. With 2+ Quick Digits: +1 Complementary Skill Check to Conceal/Reveal Object, Contortionist (hand-based), First Aid, Forgery, Language (Sign), Paramedic, Pick Lock, Pick Pocket. Install: Clinic.",
    },
    {
        "name": "Subdermal Grip",
        "type": "Cyberarm",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "Subdermal plate under the palm allows user to make use of Smartguns. A cost-effective alternative to Interface Plugs. Can be installed as the only piece of Cyberware in a meat arm. Requires Neural Link and takes up a Neuralware Option Slot.",
        "requirements": "Neural Link"
    },
{
        "name": "Techscanner",
        "type": "Cyberarm",
        "slots": 2,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Scanner diagnoses a wide variety of machinery and electronics, assisting the user in repairs or other technical work. User adds +2 to their Basic Tech, Cybertech, Land Vehicle Tech, Sea Vehicle Tech, Air Vehicle Tech, Electronics/Security Tech, and Weaponstech Skills. Requires a Cyberarm and takes 2 Option Slots. Multiple installations of this option provide user no additional benefit.",
        "requirements": "Cyberarm"
},
    {
        "name": "Wolvers",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": True,
        "damage_dice": 3,
        "damage_die_type": 6,
        "rate_of_fire": 2,
        "description": " Extendable Carbo-glass claws in the knuckles. A Heavy Melee Weapon (3d6 damage, 2 ROF) that can be successfully concealed without a Check. When wielded as a weapon, user can't hold anything in this arm's hand. Can be installed as the only piece of Cyberware in a meat arm."
    },
    {
        "name": "Cyberleg",
        "type": "Cyberleg",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "Replacement leg. Does not have to be paired. A Cyberleg has 3 Option Slots for Cyberleg or Cyberlimb Options and each comes pre-installed with a Standard Foot that doesn't cost any Humanity Loss or take up a Cyberleg Option Slot. Most Cyberleg options must be paired to work properly (purchased twice and installed in two different Cyberlegs on a user. Humanity Loss is calculated separately for each purchase)."
    },
    {
        "name": "Standard Foot",
        "type": "Cyberleg",
        "slots": 0,
        "humanity_loss": 0,
        "cost": 100,
        "is_weapon": False,
        "description": "Resembles a normal foot. If installed into a meat leg, a Standard Foot doesn't count towards the number of pieces of cyberware installed in a meat leg. Doesn't take up a Cyberleg Option Slot."
    },
    {
        "name": "Grip Foot",
        "type": "Cyberleg",
        "slots": 2,
        "humanity_loss": 6,
        "cost": 1000,
        "is_weapon": False,
        "description": "Feet are coated with state-of-the-art traction material. The user negates the normal movement penalty for climbing. Requires two Cyberlegs and must be paired.",
        "requirements": "Cyberleg"
    },
    {
        "name": "Jump Booster",
        "type": "Cyberleg",
        "slots": 4,
        "humanity_loss": 6,
        "cost": 1000,
        "is_weapon": False,
        "description": "Hydraulics in legs. Negates movement penalty when jumping. Requires two Cyberlegs, takes up 2 Option Slots, and must be paired.",
        "requirements": "Cyberleg"
    },
    {
        "name": "Skate Foot",
        "type": "Cyberleg",
        "slots": 2,
        "humanity_loss": 6,
        "cost": 1000,
        "description": "Inline skates built into feet. Can be concealed. Increases movement by 6m/yds when using Run Action. Requires two Cyberlegs and must be paired.",
        "requirements": "Cyberleg"
    },
    {
        "name": "Talon Foot",
        "type": "Cyberleg",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": True,
        "damage_dice": 1,
        "damage_die_type": 6,
        "rate_of_fire": 2,
        "description": "Blade mounted in foot. Light Melee Weapon (1d6 ROF 2). Can be concealed without a Check. Can be installed as the only piece of Cyberware in a meat leg."
    },
    {
        "name": "Web Foot",
        "type": "Cyberleg",
        "slots": 2,
        "humanity_loss": 6,
        "cost": 1000,
        "is_weapon": False,
        "description": "Thin webbing between toes. Negates movement penalty when swimming. Requires Two Cyberlegs and must be paired",
        "requirements": "Cyberleg"
    },
    {
        "name": "Rocklin Augmentics Skydrivers",
        "type": "Cyberleg",
        "slots": 0,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "Paired Cyberlegs. Must be installed together. Each has 2 Option Slots. Pre-installed Jump Boosters (no HL, no slot). Jump Boosters cannot be removed without destroying legs. After moving 4+ m/yds this Turn, Brawling/Martial Arts Attack vs cover only using legs: +3d6 damage. Install: Hospital.",
        "requirements": "Cyberleg",
    },
    {
        "name": "Hardened Shielding",
        "type": "Cyberlimb",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 1000,
        "is_weapon": False,
        "description": (
            "Clinic. Cyberlimb option. Cyberlimb and installed options cannot be rendered inoperable "
            "by EMP effects, Microwaver pulses, or Non-Black ICE program effects. Requires Cyberarm or Cyberleg."
        ),
        "requirements": "Cyberarm or Cyberleg",
    },
    {
        "name": "Plastic Covering",
        "type": "Cyberlimb",
        "slots": 0,
        "humanity_loss": 0,
        "cost": 100,
        "is_weapon": False,
        "description": "Plastic coating for Cyberlimb or Cybereye. Available in wide variety of colors and patterns. Does not take an Option Slot on limbs.",
        "requirements": "Cyberarm or Cyberleg or Cybereye",
    },
    {
        "name": "Realskinn Covering",
        "type": "Cyberlimb",
        "slots": 0,
        "humanity_loss": 0,
        "cost": 500,
        "is_weapon": False,
        "description": "Artificial skin coating for Cyberlimb or Cybereye. Does not take an Option Slot on limbs.",
        "requirements": "Cyberarm or Cyberleg or Cybereye",
    },
    {
        "name": "Superchrome Covering",
        "type": "Cyberlimb",
        "slots": 0,
        "humanity_loss": 0,
        "cost": 1000,
        "is_weapon": False,
        "description": "Shiny metallic coating for Cyberlimb or Cybereye. +2 to Style (once). Does not take an Option Slot on limbs.",
        "requirements": "Cyberarm or Cyberleg or Cybereye",
    },

    # Black Chrome Cyberarm/Cyberlimb
    {
        "name": "Neo-Soviet Cyberarm",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 100,
        "is_weapon": False,
        "description": "Replacement arm. 3 Option Slots. BODY 8+ or -1 to rolls with this arm. All options always visible. Always distinguishable as cyberarm.",
    },
    {
        "name": "Modular Finger Cyberhand",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "Cyberarm Option. Can be only cyberware in meat arm. Space for 5 Cyberfingers. Includes 5 Standard Cyberfingers. Requires Cyberarm.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Dynalar Modular Finger Enthusiast Cyberhand",
        "type": "Borgware",
        "slots": 2,
        "humanity_loss": 14,
        "cost": 500,
        "is_weapon": False,
        "description": "Cyberarm Option. Space for 8 Cyberfingers. Includes 8 Standard Cyberfingers. Requires Cyberarm, 2 Option Slots.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Flashbulb",
        "type": "Cyberarm",
        "slots": 2,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Cyberarm Option. Action: target within 25m with meat/cyber eyes makes DV15 Resist Torture/Drugs or Damaged Eye 1min. Requires Cyberarm, 2 Slots.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Integrated Cyberdeck Upgrade",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Cyberarm Option. +1 slot (Program or Hardware) to arm-integrated Cyberdeck. Same arm only.",
        "requirements": "Cyberarm with Cyberdeck",
    },
    {
        "name": "Popup Net Launcher",
        "type": "Cyberarm",
        "slots": 3,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Cyberarm Option. Exotic net launcher, 1 net, 1 ROF, Shoulder Arms, max 25m. On hit: grapple, no Move, -2 physical Actions. Net 15 HP. Requires Cyberarm, 3 Slots.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Popup Shotgun",
        "type": "Cyberarm",
        "slots": 3,
        "humanity_loss": 7,
        "cost": 1000,
        "is_weapon": False,
        "description": "Cyberarm Option. Shotgun, 2 shots, Smartgun Link only. Concealed, draw/stow no Action. Requires Cyberarm, 3 Slots.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Reinforced Cyberlimb Upgrade",
        "type": "Cyberlimb",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 1000,
        "is_weapon": False,
        "description": (
            "Cyberlimb option. Increased hydraulic redundancy and bracing: immune to the Broken Leg "
            "critical injury on a Cyberleg, or Broken Arm on a Cyberarm; the GM decides which limb is "
            "targeted when you suffer a critical injury unless otherwise stated. Requires Cyberarm or Cyberleg."
        ),
        "requirements": "Cyberarm or Cyberleg",
    },
    {
        "name": "Extra-Jointed Cyberlimb Upgrade",
        "type": "Cyberlimb",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": False,
        "description": "Cyberlimb Option. +2 to Contortionist Skill Checks. One per cyberlimb. Max 4 cyberlimbs for +8 total. Requires Cyberarm or Cyberleg.",
        "requirements": "Cyberlimb",
    },
    # Black Chrome Cyberfingers (require Modular Finger Cyberhand)
    {
        "name": "Standard Cyberfinger",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 0,
        "cost": 20,
        "is_weapon": False,
        "description": "Cyberfinger. No special features. Requires Modular Finger Cyberhand.",
        "requirements": "Modular Finger Cyberhand",
    },
    {
        "name": "Dartgun Cyberfinger",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": True,
        "damage_dice": 1,
        "damage_die_type": 6,
        "rate_of_fire": 1,
        "description": "Cyberfinger. Dartgun Exotic Weapon, 1 shot. Concealed with glove. Requires Modular Finger Cyberhand.",
        "requirements": "Modular Finger Cyberhand",
    },
    {
        "name": "Lockpick Cyberfinger",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "Cyberfinger. Adjustable lockpick. All you need for non-electronic locks. Requires Modular Finger Cyberhand.",
        "requirements": "Modular Finger Cyberhand",
    },
    {
        "name": "Lighter Cyberfinger",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "Cyberfinger. Concealed lighter in fingertip. Requires Modular Finger Cyberhand.",
        "requirements": "Modular Finger Cyberhand",
    },
    {
        "name": "Homing Tracer Cyberfinger",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": False,
        "description": "Cyberfinger. Points to linked tracer within 1 mile. Includes fingernail tracer. Replacements 50eb. Requires Modular Finger Cyberhand.",
        "requirements": "Modular Finger Cyberhand",
    },
    # Add more Cyberlimb items -- Leaving open in case of new book releases.


    # Borgware
    {
        "name": "Artificial Shoulder Mount",
        "type": "Borgware",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "User can mount 2 Cyberarms under first set of arms. User can only have one Artificial Shoulder Mount installed."
    },
    {
        "name": "Implanted Linear Frame Sigma",
        "type": "Borgware",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "An enhanced skeleton and support structure with hydraulic and myomar muscles. User increases their BODY to 12. This increase in BODY changes a Character's HP and Death Save. This cannot increase the user's BODY to 13 or higher. Installation requires BODY 6 and Grafted Muscle and Bone Lace."
    },
    {
        "name": "Implanted Linear Frame Beta",
        "type": "Borgware",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 5000,
        "is_weapon": False,
        "description": "A heavily enhanced skeleton and support structure with even more hydraulic and myomar muscles. User increases their BODY to 14. This increase in BODY changes a Character's HP and Death Save. This cannot increase the user's BODY to 15 or higher. Installation requires BODY 8 and Two Grafted Muscle and Bone Lace."
    },
    {
        "name": "MultiOptic Mount",
        "type": "Borgware",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "User can mount up to 5 additional Cybereyes into the MultiOptic Mount. Cybereyes sold and installed separately. User can only have one MultiOptic Mount installed."
    },
    {
        "name": "Sensor Array",
        "type": "Borgware",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "Twin flattened antennae protruding from the user's head improving their Cyberaudio Suite, sometimes referred to as 'Rabbit Ears.' User can install up to 5 additional Cyberaudio Options into their Cyberaudio Suite. User can only have one Sensor Array installed. Requires Cyberaudio Suite but doesn't take up a Cyberaudio Option Slot.",
        "requirements": "Cyberaudio Suite"
    },
    {
        "name": "Zetatech CyberConductor, Integrated",
        "type": "Borgware",
        "slots": 3,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "Internal Body Cyberware. May only be installed in Full Body Conversion. Installed in FBC body. Connects all FBC cyberdecks to CyberConductor; switch between any of them. No damage when switching. Cyberdecks count as Integrated for FBC Bodyweight Coating etc. Only one CyberConductor. Install: Hospital.",
    },
    # Black Chrome Borgware
    {
        "name": "Borgware Hardened Shielding",
        "type": "Borgware",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "One piece of installed Borgware (e.g. Linear Frame) immune to electric shock, microwaver, EMP, Non-Black ICE program effects.",
    },
    # Edgerunners Mission Kit cyberware (2070s)
    {
        "name": "Berserk Implant",
        "type": "Neuralware",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 1000,
        "is_weapon": False,
        "description": "Neuralware Option. Hormone regulation implant for fight-or-flight. Action to activate: ignore Seriously and Mortally Wounded effects for 60 seconds (20 Rounds); Mortally Wounded still make Death Saves. 1hr cooldown before reactivation.",
    },
    {
        "name": "Experimental Sandevistan",
        "type": "Borgware",
        "slots": 2,
        "humanity_loss": 14,
        "cost": 250000,
        "is_weapon": False,
        "description": "Neuralware Option. Borgware. Speedware. 2 slots. Activation: 2d6 HL (no Action, even during combat). Top of Initiative. If activated on your Turn: +1 Move or Action. Negative Humanity: take HL as direct HP damage (bypasses armor). Extreme Cyberpsychosis if negative. Only one Speedware.",
    },
    {
        "name": "Ex-Disk",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 1000,
        "is_weapon": False,
        "description": "Neuralware. Requires Neuroport Cyberdeck Port. +1 Hardware-only slot for Cyberdeck. Hardware in Ex-Disks counts as installed in any deck in Neuroport. 2+ Ex-Disks: +1 NET Action when physically connected to Access Point via Interface Plug.",
        "requirements": "Neuroport Cyberdeck Port",
    },
    {
        "name": "Gorilla Arm",
        "type": "Cyberarm",
        "slots": 2,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": True,
        "damage_dice": 3,
        "damage_die_type": 6,
        "rate_of_fire": 2,
        "description": "Cyberarm Option. 2 slots. Excellent Quality Heavy Melee Weapon. Wield weapons in this arm as BODY 11. Paired (both arms): pry doors, move Thick Cover, Choke, Slam as BODY 11. Requires Cyberarm, 2 slots.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Mantis Blade",
        "type": "Cyberarm",
        "slots": 2,
        "humanity_loss": 14,
        "cost": 500,
        "is_weapon": True,
        "damage_dice": 3,
        "damage_die_type": 6,
        "rate_of_fire": 2,
        "description": "Cyberarm Option. 2 slots. One-Handed Excellent Quality Heavy Melee. Concealed without Check, draw/stow no Action. Popped up: cannot hold in hand. Paired (both arms): negate climb movement penalty. Requires Cyberarm, 2 slots.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Monowire",
        "type": "Cyberarm",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 1000,
        "is_weapon": True,
        "damage_dice": 3,
        "damage_die_type": 6,
        "rate_of_fire": 2,
        "description": "Cyberarm Option. Monofilament whip. One-Handed Exotic Heavy Melee, 6m range. Concealed without Check. Critical: roll twice on table, choose result. Requires Cyberarm.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Neuroport",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 0,
        "cost": 1000,
        "is_weapon": False,
        "description": "2070s control package. Neural Link (5 slots), Holophone, Biomonitor, Virtu, HUD, 2 Shard Slots, Personal Link. No additional Option Slots taken. Required for non-medical cyberware. Quickhack target.",
    },
    {
        "name": "Neuroport Cyberdeck Port",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "Requires Neuroport. Neck port for Cyberdeck. Install/uninstall as Action. Range: 20m NET, 50m Neuroports. No Hardware options on Neuroport decks.",
        "requirements": "Neuroport",
    },
    {
        "name": "Projectile Launch System",
        "type": "Borgware",
        "slots": 2,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "Cyberarm Option. Borgware. 2 slots. Rocket Launcher or Grenade Launcher, 1 round. Incompatible with all weapon attachments except Smart Rebuild. Concealed without Check, draw/stow no Action. Popped up: cannot hold in hand. Requires Cyberarm, 2 slots.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Self-ICE",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": False,
        "description": "Max 3. Each: +1 Passwall in Neuroport. DV: 1=DV6, 2=DV8, 3=DV10. Protects vs Quickhacks.",
    },
    # Interface RED Vol 3: Must Have Cyberware Deals
    {
        "name": "Appetite Controller",
        "type": "Internal Body Cyberware",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Manage and ignore hunger at touch of button via Biomonitor. Ignore Humanity Loss from Long-term Environmental Stress (starvation). Starvation still an issue: after 7 days without food, Death Save at day start with cumulative +1 per additional day. Requires Biomonitor.",
        "requirements": "Biomonitor",
    },
    {
        "name": "Cyberpillow",
        "type": "Cyberarm Option",
        "slots": 1,
        "humanity_loss": 0,
        "cost": 100,
        "is_weapon": False,
        "description": "Pillow pops from cyberarm for napping. Multiple do nothing extra. Requires Cyberarm.",
        "requirements": "Cyberarm",
    },
    {
        "name": "External Vidscreen",
        "type": "External Body Cyberware",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 100,
        "is_weapon": False,
        "description": "Flexible touch panel installed subcutaneously. Links to Agent or Memory Chip in Chipware Socket. Body part becomes screen.",
    },
    {
        "name": "Holo Projector Palm",
        "type": "Cyberarm Option",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "Hologram projector in palm. Soda-can sized interactive projection when linked to Agent. Can be only cyberware in meat arm.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Kill Display",
        "type": "Fashionware",
        "slots": 1,
        "humanity_loss": 0,
        "cost": 100,
        "is_weapon": False,
        "description": "KILLS: [number] on forearm. Self-reported via Agent, max 999. Counts as Light Tattoo for +2 Style (three installs).",
    },
    {
        "name": "Lead's Turn-On Show-Off Nails",
        "type": "Fashionware",
        "slots": 1,
        "humanity_loss": 0,
        "cost": 100,
        "is_weapon": False,
        "description": "10 programmable lighted fingernails. Light pens for presets. CitiNet downloads via Agent. Counts as Light Tattoo. Meat or cyber hands.",
    },
    {
        "name": "Mood Eye",
        "type": "Fashionware",
        "slots": 1,
        "humanity_loss": 0,
        "cost": 100,
        "is_weapon": False,
        "description": "Color-changing lenses. Eye color reflects mood (red=anger, blue=sadness, yellow=fear, etc.). DV21 Acting to fake. Deactivate anytime. Requires Neural Link.",
        "requirements": "Neural Link",
    },
    {
        "name": "NeuTongue",
        "type": "Internal Body Cyberware",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 100,
        "is_weapon": False,
        "description": "Cybernetic tongue alters sense of taste. Virtual seasoning via linked Agent. Can be deactivated anytime without Action to eliminate sense of taste.",
    },
    {
        "name": "PerfectFit Cyberfoot",
        "type": "Cyberleg Option",
        "slots": 1,
        "humanity_loss": 2,
        "cost": 100,
        "is_weapon": False,
        "description": "Action: change foot size Euro 0 to US 37AA. Zero penalty for ill-fitting footwear. Can be only cyberware in meat leg.",
        "requirements": "Cyberleg",
    },
    {
        "name": "PersonalPak KibbleWarmer",
        "type": "Cyberarm Option",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "Cylindrical rotisserie oven in forearm for PersonalPak Kibble. Requires Cyberarm.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Pursuit Security Inc. Personal Shredder",
        "type": "Cyberarm Option",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "Cross-cut shredder in cyberarm with internal reservoir. Requires Cyberarm.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Sponsored Covering",
        "type": "Cyberlimb Option",
        "slots": 0,
        "humanity_loss": 0,
        "cost": 50,
        "is_weapon": False,
        "description": "Illuminated ad on limb. Good standing + display uncovered = 20eb/month. Does not take Option Slot. Requires Cyberarm or Cyberleg.",
        "requirements": "Cyberarm or Cyberleg",
    },
    # Interface RED Vol 3: The 12 Days of Cybermas
    {
        "name": "ChainRipp",
        "type": "Cyberarm Option",
        "slots": 4,
        "humanity_loss": 14,
        "cost": 500,
        "is_weapon": True,
        "damage_dice": 4,
        "damage_die_type": 6,
        "rate_of_fire": 1,
        "description": "Chainsaw in wrist. Draw/stow no Action. Action to rev: Excellent Quality Very Heavy Melee until stowed. Requires Cyberarm.",
        "requirements": "Cyberarm",
    },
    {
        "name": "CyberMatrix Gang Jazzler",
        "type": "Cyberarm Option",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Concealed electrode. During Choke: expend 50eb battery, target DV13 Resist Torture/Drugs or Unconscious 1 min. Can be only cyberware in meat arm.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Cyclops International Bug Eye",
        "type": "Borgware",
        "slots": 0,
        "humanity_loss": 14,
        "cost": 500,
        "is_weapon": False,
        "description": "Oversized cybereye. 5 slots for Cybereye Options.",
    },
    {
        "name": "DeathTrance",
        "type": "Neuralware",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 500,
        "is_weapon": False,
        "description": "Action: vitals slow, -4 to Actions. Appears dead. DV17 Medical Tech or DV21 Criminology/Deduction/Perception to detect. Exit anytime.",
    },
    {
        "name": "Kiroshi MonoVision",
        "type": "Borgware",
        "slots": 0,
        "humanity_loss": 14,
        "cost": 500,
        "is_weapon": False,
        "description": "Single cyberoptic replaces both eyes. 3 Cybereye Option slots. Options count as paired. Lost Eye Critical doubled.",
    },
    {
        "name": "Kiroshi OptiShield",
        "type": "External Body Cyberware",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Retractable Anti-Dazzle mirrorshades in brow. Action to extend/retract. Immune to flashbang blindness.",
    },
    {
        "name": "PsiBerstuff Watch-Man",
        "type": "Cyberarm Option",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "Fully functional Agent with flip-up screen in cyberarm.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Poser Chip",
        "type": "Chipware",
        "slots": 1,
        "humanity_loss": 14,
        "cost": 500,
        "is_weapon": False,
        "description": "Chipware. +4 Acting to impersonate persona. +5 if not fighting it. Famous (public footage): 500eb. Private (10+ hrs): 1000eb. Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    },
    {
        "name": "Radline Blitzkrieg Arc-Thrower Cyberarm",
        "type": "Cyberarm",
        "slots": 0,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": True,
        "damage_dice": 4,
        "damage_die_type": 6,
        "rate_of_fire": 1,
        "description": "Cyberarm, no hand. Poor Quality Exotic Shotgun, Heavy Weapons. 32 charges, 1hr recharge. No Critical Injury, no ablation. Unconscious at 1 HP if would kill.",
        "requirements": None,
    },
    {
        "name": "Raven Microcybernetics MicroWaldo",
        "type": "Cyberarm Option",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 1000,
        "is_weapon": False,
        "description": "Medtech +1 Surgery Skill. 8 articulated probes. Requires Cyberarm.",
        "requirements": "Cyberarm",
    },
    {
        "name": "Sycust Fleshweave",
        "type": "External Body Cyberware",
        "slots": 1,
        "humanity_loss": 7,
        "cost": 1000,
        "is_weapon": False,
        "description": "Skinweave SP7 body and head. 10 min without strenuous activity: repairs to full SP.",
    },
    # Interface RED Vol 2
    {
        "name": "Combat Tail",
        "type": "External Body Cyberware",
        "slots": 2,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": True,
        "description": "Spine extended to connect nerves to weaponized tail module. Functions as Heavy Melee Weapon. At GM discretion, may be used for other tasks at -4 penalty (cannot be used as weapon during). Requires Neural Link.",
        "requirements": "Neural Link",
    },
    {
        "name": "Firebreather",
        "type": "Internal Body Cyberware",
        "slots": 2,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": True,
        "description": "Exotic shotgun in throat, fired by opening mouth and hyperextending tongue. Incompatible with weapon attachments. Single incendiary shell only. Complete mouth/nose/throat rebuild. Can be concealed without Check.",
    },
    # Danger Gal Dossier
    {
        "name": "Combat Jaw",
        "type": "External Body Cyberware",
        "slots": 2,
        "humanity_loss": 14,
        "cost": 500,
        "is_weapon": True,
        "description": "Jaw replaced with hydraulic jaw capable of devastating bite force. Two rows of reinforced teeth. Functions as Very Heavy Melee Weapon.",
    },
    {
        "name": "Wyzard Technologies Romanova Cyberlegs",
        "type": "Cyberleg",
        "slots": 0,
        "humanity_loss": 14,
        "cost": 1000,
        "is_weapon": False,
        "description": "Paired Cyberlegs. 3 Option Slots each. Pre-installed Talon Foot (no HL, no slot). Talon cannot be removed.",
        "requirements": None,
    },
    # Interface RED Vol 4: Hornet's Pharmacy
    {
        "name": "Bodyweight Autoinjector",
        "type": "Internal Body Cyberware",
        "slots": 1,
        "humanity_loss": 3,
        "cost": 100,
        "is_weapon": False,
        "description": "Subdermal reservoir. Load one dose of Street Drug as Action; inject as Action. With Biomonitor: program auto-inject on Initiative, Critical Injury, or chosen Wound State.",
    },
    {
        "name": "Pursuit Security Inc Gas Jet",
        "type": "Cyberarm",
        "slots": 2,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Aerosol gas launcher. 3 doses Street Drug or Poison/Biotoxin. Concealable. One-handed Exotic Shotgun, 1-shot, Shotgun Shell mode only. Hit applies loaded substance. Nasal Filters negate. Requires Cyberarm.",
        "requirements": "Cyberarm",
    },
    # Interface RED Vol 4: 12 Days of Gearmas
    {
        "name": "Cyberscanner, Integrated",
        "type": "Cyberarm",
        "slots": 2,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "description": "Cyberscanner in Cyberarm. Readout on arm LED, Chyron, or Agent. Scan 2 m/yds, 1 minute, target still. Hardened/Tech-Upgraded/unknown chrome = error. Requires Cyberarm.",
        "requirements": "Cyberarm",
    },
]

# Bodysculpt packages: when purchased, all listed cyberware is added to the character.
# Package cost and humanity_loss are the total for the package.
BODYCULPT_PACKAGES = {
    "Demonique": {
        "cost": 2100,
        "humanity_loss": 14,
        "description": "Dark and Mysterious. Biotechnica's most sensual Exotic. Never worry about shoes again when you can wear hooves. Be the devil on your own shoulder. Includes 31 day stay at The Zoo.",
        "package_contains": ["Combat Tail", "Cyberaudio Suite", "Voice Stress Analyzer", "Cyberleg", "Neural Link", "Subdermal Armor"],
    },
    "Embrace Rodentia": {
        "cost": 2100,
        "humanity_loss": 16,
        "description": "You've always been a street rat. Better make it official. Latest generation rodent Bioexotic, most customizable edition. Custom Sensor Array ears in rodent shapes: Chipmunk, Mink, Ferret, Field Mouse, and more. Includes 31 day stay at The Zoo.",
        "package_contains": ["Cyberaudio Suite", "Amplified Hearing", "Cybereye", "Low Light-IR-UV", "Sensor Array"],
    },
    "Katnip": {
        "cost": 2200,
        "humanity_loss": 18,
        "description": "Feeling feline? Land like a cat. No kitty complete without claws. Best-selling Exotic Bodysculpt for 25 years. Includes 31 day stay at The Zoo.",
        "package_contains": ["Cybereye", "Cybereye", "Low Light-IR-UV", "Low Light-IR-UV", "Cyberleg", "Cyberleg", "Grafted Muscle and Bone Lace", "Scratchers", "Scratchers"],
    },
    "Lagoform": {
        "cost": 2100,
        "humanity_loss": 16,
        "description": "Be your own good luck charm! Premium Rocklin Augmentics Jump Boosters. Fluffy tail optional. Includes 31 day stay at The Zoo.",
        "package_contains": ["Cyberaudio Suite", "Amplified Hearing", "Cyberleg", "Cyberleg", "Jump Booster", "Jump Booster", "Sensor Array"],
    },
    "Lupaform": {
        "cost": 2200,
        "humanity_loss": 20,
        "description": "Not everyone is a cat person. Biotechnica's most cosmetically customizable Bioexotic. If it has four legs and could catch a ball, there's a LupaForm for that. Includes 31 day stay at The Zoo.",
        "package_contains": ["Chipware Socket", "Olfactory Boost", "Combat Jaw", "Cyberaudio Suite", "Amplified Hearing", "Cybereye", "Low Light-IR-UV", "Neural Link"],
    },
    "Serpentize Yourself": {
        "cost": 2100,
        "humanity_loss": 16,
        "description": "Do you find mammals unappealing? Do your veins run cold? 25th anniversary edition, Biotechnica's most seductive snake form. Get your tongue forked today. Includes 31 day stay at The Zoo.",
        "package_contains": ["Chipware Socket", "Olfactory Boost", "Cybereye", "Low Light-IR-UV", "Neural Link", "Vampyres"],
    },
    "Aquaform": {
        "cost": 4500,
        "humanity_loss": 22,
        "description": "Luxurious AquaForm. Delight of ocean lovers and lawyers for 25 years. Re-textured aquadynamic shark skin. Also available in Seal, Dolphin, Orca. Includes 31 day stay at The Zoo.",
        "package_contains": ["Combat Jaw", "Cybereye", "Cybereye", "Low Light-IR-UV", "Low Light-IR-UV", "Cyberleg", "Cyberleg", "Web Foot", "Web Foot", "Gills", "Radar Sonar Implant"],
    },
    "Bigkatt": {
        "cost": 7000,
        "humanity_loss": 36,
        "description": "When KatNip isn't enough, go big. Concrete jungle's latest predator. Lion, tiger, liger, tigon, puma, cheetah, and more. Includes 31 day stay at The Zoo.",
        "package_contains": ["Neural Link", "Cybereye", "Cybereye", "Low Light-IR-UV", "Cyberleg", "Cyberleg", "Grip Foot", "Grip Foot", "Jump Booster", "Jump Booster", "Grafted Muscle and Bone Lace", "Grafted Muscle and Bone Lace", "Reflex Co-Processor", "Sandevistan", "Combat Jaw", "Wolvers", "Wolvers"],
    },
    "Bughouse": {
        "cost": 6600,
        "humanity_loss": 48,
        "description": "Step sideways on the evolutionary scale. 25th anniversary. Truly rare and exotic form. Biotechnica's number one most satisfied Bioexotics responders. When it's time to bug out, trust Biotechnica. Includes 31 day stay at The Zoo.",
        "package_contains": ["Cyberarm", "Cyberarm", "Extra-Jointed Cyberlimb Upgrade", "Extra-Jointed Cyberlimb Upgrade", "Cybereye", "Cybereye", "Cybereye", "Cybereye", "Cybereye", "Cybereye", "Image Enhance", "Image Enhance", "Low Light-IR-UV", "Low Light-IR-UV", "MicroOptics", "Cyberleg", "Cyberleg", "Extra-Jointed Cyberlimb Upgrade", "Extra-Jointed Cyberlimb Upgrade", "Jump Booster", "Jump Booster", "MultiOptic Mount", "Combat Jaw"],
    },
    "NeuHuman": {
        "cost": 4000,
        "humanity_loss": 32,
        "description": "Embrace the Neu. Your form perfected, defended, confident. Custom NeuHuman Bodysculpt. Turn heads, take action on street and boardroom. Includes Health Monitor and 31 day stay at The Zoo.",
        "package_contains": ["Appetite Controller", "Biomonitor", "Chipware Socket", "Pain Editor", "Cybereye", "Cybereye", "Anti-Dazzle", "Anti-Dazzle", "Chyron", "Cyberaudio Suite", "Level Damper", "Internal Agent", "Enhanced Antibodies", "Heuristic Health Monitor", "Nasal Filters", "Neural Link", "Reflex Co-Processor", "NeuTongue", "Toxin Binders"],
    },
    "Ursaform": {
        "cost": 8200,
        "humanity_loss": 52,
        "description": "Biotechnica's most enhanced Bioexotic. Pride of research division. Change your life in a beary good way. Psychological evaluation provided. Unseen side effects can result in brief cyberpsychosis. Requires BODY 4+ for Linear Frame Sigma. Includes 31 day stay at The Zoo.",
        "package_contains": ["Chipware Socket", "Pain Editor", "Chipware Socket", "Olfactory Boost", "Combat Jaw", "Cyberarm", "Cyberarm", "Wolvers", "Wolvers", "Cyberaudio Suite", "Amplified Hearing", "Cybereye", "Cybereye", "Low Light-IR-UV", "Low Light-IR-UV", "Cyberleg", "Cyberleg", "Grip Foot", "Grip Foot", "Grafted Muscle and Bone Lace", "Implanted Linear Frame Sigma", "Neural Link"],
    },
    "Draconic Fantaform": {
        "cost": 11000,
        "humanity_loss": 34,
        "description": "Original and ultimate FantaForm. 25 years development. Fire-breathing mouth. Train at Bioexotics camp, fight Dwarven FantaForm adventurers in mountain lair LARP finale. Requires BODY 4+ for Linear Frame Beta. Includes 31 day stay at The Zoo.",
        "package_contains": ["Combat Jaw", "Combat Tail", "Cyberarm", "Cyberarm", "Cybereye", "Cybereye", "Cyberleg", "Cyberleg", "Firebreather", "Grafted Muscle and Bone Lace", "Grafted Muscle and Bone Lace", "Implanted Linear Frame Beta", "Neural Link", "Subdermal Armor", "Wolvers", "Wolvers"],
    },
    "Dwarvish Fantaform": {
        "cost": 2100,
        "humanity_loss": 12,
        "description": "Heartiest and bravest Dwarves made at Bioexotics camp. Exclusive LARP trek through Blue Mountains. Dungeons deep, caverns old, long forgotten gold. Includes 31 day stay at The Zoo.",
        "package_contains": ["Cybereye", "Cybereye", "Low Light-IR-UV", "Low Light-IR-UV", "Grafted Muscle and Bone Lace", "Toxin Binders"],
    },
    "Elvish Fantaform": {
        "cost": 2100,
        "humanity_loss": 16,
        "description": "Take your Elf Life Offline. Live full time as your Elflines Online character. Forest LARP of a Lifetime. Come home a real Elf. Includes 31 day stay at The Zoo.",
        "package_contains": ["Cyberaudio Suite", "Amplified Hearing", "Cybereye", "Cybereye", "Image Enhance", "Image Enhance", "Low Light-IR-UV", "Low Light-IR-UV"],
    },
    "Merish Fantaform": {
        "cost": 3600,
        "humanity_loss": 24,
        "description": "At home under waves and on land. Month underwater off Oregon in LARPlantis. Get used to new body with campmates, solve murder mystery. One participant chosen as murderer. Includes 31 day stay at The Zoo.",
        "package_contains": ["Chipware Socket", "Tactile Boost", "Cybereye", "Cybereye", "Low Light-IR-UV", "Low Light-IR-UV", "Cyberleg", "Cyberleg", "Web Foot", "Web Foot", "Gills", "Neural Link"],
    },
    "Ogrish Fantaform": {
        "cost": 4000,
        "humanity_loss": 12,
        "description": "Feel invincible. Same military grade Pain Editor Militech trusts. Trained to lead Orcish Fantaform soldiers in LARP by real Militech Operative. Biotechnica not responsible for injuries. Includes 31 day stay at The Zoo.",
        "package_contains": ["Chipware Socket", "Pain Editor", "Enhanced Antibodies", "Grafted Muscle and Bone Lace", "Neural Link", "Subdermal Armor"],
    },
    "Orcish Fantaform": {
        "cost": 2500,
        "humanity_loss": 12,
        "description": "Crave blood and battle? Forged in heat of war and death at Bioexotics camp. Martial campaign LARP against bodysculpted actors. Earn your place as real Orc. Shameful to become Orc any other way. Biotechnica not responsible for injuries. Includes 31 day stay at The Zoo.",
        "package_contains": ["Cybereye", "Cybereye", "Low Light-IR-UV", "Low Light-IR-UV", "Grafted Muscle and Bone Lace", "Skin Weave"],
    },
}

# Basic skills (1x cost) - each gets a Basic Skill Chip
BASIC_SKILLS = [
    "concentration", "conceal_object", "lip_reading", "perception", "tracking",
    "athletics", "contortionist", "dance", "endurance", "resist_torture_drugs", "stealth",
    "brawling", "evasion", "melee", "pick_pocket",
    "archery", "handgun", "shoulder_arms", "drive_land", "pilot_sea", "riding",
    "accounting", "animal_handling", "bureaucracy", "business", "composition", "criminology",
    "cryptography", "deduction", "education", "gamble", "library_search",
    "zoology", "physics", "stock_market", "biology", "chemistry", "neuroscience",
    "data_science", "economics", "sociology", "political_science", "genetics", "anatomy",
    "robotics", "nanotechnology", "tactics", "wilderness_survival",
    "air_vehicle_tech", "artistry", "basic_tech", "cybertech", "first_aid", "forgery",
    "land_vehicle_tech", "photography", "pick_lock", "sea_vehicle_tech", "weaponstech",
    "acting", "bribery", "interrogation", "personal_grooming", "persuasion", "streetwise", "style", "trading",
    "conversation", "human_perception",
]
# Advanced skills (2x cost) - each gets an Advanced Skill Chip
ADVANCED_SKILLS = ["autofire", "heavy_weapons", "demolitions", "electronics_security_tech", "paramedic", "pilot_air"]

# Martial Arts is double-cost; each style is its own Advanced Skill Chip.
# skill_chip_target uses lowercase instance with spaces (e.g. martial_arts(krav maga)) so it matches +roll / IP lookups.
MARTIAL_ARTS_STYLES = sorted([
    "Aikido",
    "Arasaka-te",
    "Arnis",
    "Boxing",
    "Capoeira",
    "Choy Li Fut",
    "Drunken Fist",
    "Gun Fu",
    "Judo",
    "Jujutsu",
    "Jujitsu",  # alternate spelling / legacy
    "Karate",
    "Kendo",
    "Krav Maga",
    "Kung Fu",
    "Kyudo",
    "Militech Commando Training",
    "Muay Thai",
    "Multiarm Melee",
    "PanzerFaust",
    "Silat",
    "Sov-System",
    "Sumo",
    "Tai Chi",
    "Taekwondo",
    "Tae Kwon Do",  # alternate spelling / legacy chars
    "Thamoc",
    "Thrash Sambo",
    "Wrestling",
], key=str.lower)

# Local Expert / Play Instrument are 1x skills; chips must target the instance (base-only never matches rolls).
LOCAL_EXPERT_AREAS = [
    # Core / player-requested regions
    "Night City",
    "The Net",
    "Badlands",
    "Corporate Zones",
    "Del Coronado Bay",
    "Dogtown",
    "Watson",
    "Santo Domingo",
    "Pacifica",
    "NorCal Highways",
    # Extra districts / travel hubs (CP Red map + common games)
    "Westbrook",
    "Heywood",
    "City Center",
    "Japantown",
    "Little China",
    "Vista Del Rey",
    "Northside",
    "The Glen",
    "Rancho Coronado",
    "Combat Zone",
    "Orbital",
    "Crystal Palace",
    "Los Angeles",
    "Tokyo",
    "London",
    "Atlanta",
]

PLAY_INSTRUMENT_VARIANTS = [
    "Singing",
    "Guitar",
    "Violin",
    "Cello",
    "Piano",
    "Drums",
    "Bass",
    "Synth",
    "Brass Instruments",
    "Woodwinds",
]

def _skill_display(skill_key):
    from world.list_data import SKILL_DISPLAY_OVERRIDES
    base = skill_key.split("(")[0] if "(" in skill_key else skill_key
    return SKILL_DISPLAY_OVERRIDES.get(base, base.replace("_", " ").title())

for skill in BASIC_SKILLS:
    display = _skill_display(skill)
    CYBERWARE_DATA_LIST.append({
        "name": f"Basic Skill Chip ({display})",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "skill_chip_target": skill,
        "description": f"Chipware. While installed, grants {display} at +3 unless your natural rating is higher. Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    })
for skill in ADVANCED_SKILLS:
    display = _skill_display(skill)
    CYBERWARE_DATA_LIST.append({
        "name": f"Advanced Skill Chip ({display})",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 1000,
        "is_weapon": False,
        "skill_chip_target": skill,
        "description": f"Chipware. While installed, grants {display} at +3 unless your natural rating is higher. Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    })
for style in MARTIAL_ARTS_STYLES:
    inst = style.strip().lower()
    CYBERWARE_DATA_LIST.append({
        "name": f"Advanced Skill Chip (Martial Arts: {style})",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 1000,
        "is_weapon": False,
        "skill_chip_target": f"martial_arts({inst})",
        "description": f"Chipware. While installed, grants Martial Arts ({style}) at +3 unless your natural rating is higher. Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    })

for area in LOCAL_EXPERT_AREAS:
    inst = area.strip().lower()
    CYBERWARE_DATA_LIST.append({
        "name": f"Basic Skill Chip (Local Expert: {area})",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "skill_chip_target": f"local_expert({inst})",
        "description": f"Chipware. While installed, grants Local Expert ({area}) at +3 unless your natural rating is higher. Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    })

for instrument in PLAY_INSTRUMENT_VARIANTS:
    inst = instrument.strip().lower()
    CYBERWARE_DATA_LIST.append({
        "name": f"Basic Skill Chip (Play Instrument: {instrument})",
        "type": "Neuralware",
        "slots": 0,
        "humanity_loss": 7,
        "cost": 500,
        "is_weapon": False,
        "skill_chip_target": f"play_instrument({inst})",
        "description": f"Chipware. While installed, grants Play Instrument ({instrument}) at +3 unless your natural rating is higher. Requires Chipware Socket.",
        "requirements": "Chipware Socket",
    })

# Add bodysculpt packages as Cyberware entries so they appear in catalogs
for pkg_name, pkg_data in BODYCULPT_PACKAGES.items():
    CYBERWARE_DATA_LIST.append({
        "name": pkg_name,
        "type": "Bodysculpt Package",
        "slots": 0,
        "humanity_loss": pkg_data["humanity_loss"],
        "cost": pkg_data["cost"],
        "is_weapon": False,
        "description": pkg_data["description"] + " Package contains: " + ", ".join(pkg_data["package_contains"]),
    })

CYBERWARE_DATA = {item['name']: item for item in CYBERWARE_DATA_LIST}