# Generated by Django 5.2.8 on 2026-03-10 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cyberpunk_sheets", "0002_initial"),
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mystery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "goal",
                    models.TextField(
                        help_text="End state: e.g., who stole the cyberware."
                    ),
                ),
                (
                    "max_complexity",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Initial Complexity. When reduced to 0, mystery is solved.",
                    ),
                ),
                ("current_complexity", models.PositiveIntegerField(default=50)),
                ("is_solved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_mysteries",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MysteryClue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clue_type",
                    models.CharField(
                        help_text="auditing, autopsy, forensics, gossip, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "skills_used",
                    models.CharField(
                        help_text="Comma-separated: accounting, bureaucracy",
                        max_length=200,
                    ),
                ),
                ("dv", models.PositiveIntegerField(default=13)),
                ("damage_dice", models.CharField(default="3d6", max_length=20)),
                ("focus_damage_dice", models.CharField(default="2d6", max_length=20)),
                ("obfuscation", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "mystery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clues",
                        to="mystery.mystery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CharacterFocus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_focus",
                    models.IntegerField(
                        default=0,
                        help_text="Depletes on failed Evidence Checks. At 0 or below, cannot make Evidence Checks.",
                    ),
                ),
                (
                    "character_object",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mystery_focus",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "character_sheet",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mystery_focus",
                        to="cyberpunk_sheets.charactersheet",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("character_sheet__isnull", False),
                            ("character_object__isnull", False),
                            _connector="OR",
                        ),
                        name="mystery_focus_has_character",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClueAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempted_date",
                    models.DateField(
                        help_text="Used to enforce one Evidence Check per Clue per day."
                    ),
                ),
                ("success", models.BooleanField(default=False)),
                ("damage_dealt", models.PositiveIntegerField(default=0)),
                ("focus_lost", models.PositiveIntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clue_attempts",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "clue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mystery.mysteryclue",
                    ),
                ),
            ],
            options={
                "unique_together": {("clue", "character", "attempted_date")},
            },
        ),
    ]
