# Generated by Django 5.2.8

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
        ("mystery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClueLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="mystery.mysteryclue",
                    ),
                ),
                (
                    "location_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mystery_clues",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "unique_together": {("clue", "location_object")},
            },
        ),
    ]
