# Generated by Django 5.2.8

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission_board", "0001_initial"),
        ("mystery", "0002_cluelocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="mystery",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mysteries",
                to="mission_board.mission",
            ),
        ),
        migrations.AddField(
            model_name="mysteryclue",
            name="linked_clues",
            field=models.ManyToManyField(
                blank=True,
                related_name="linked_to",
                to="mystery.mysteryclue",
            ),
        ),
        migrations.AddField(
            model_name="mysteryclue",
            name="required_clues",
            field=models.ManyToManyField(
                blank=True,
                related_name="unlocks",
                to="mystery.mysteryclue",
            ),
        ),
    ]
