from .models import Program, Hardware

"""
Model for Copy/paste
"name": "",
"type": "",
"atk": ,
"dfv": ,
"rez": ,
"effect": "",
"cost": ,
"icon": "
"""
programs = [
    {
    "name": "Eraser",
    "type": "booster",
    "atk": 0,
    "dfv": 0,
    "rez": 7,
    "effect": "Increases all Cloak Checks you make by +2 as long as this Program remains rezzed.",
    "cost": 20,
    "icon": "A pink glob exuding tiny soap bubbles.",
    },
    {
    "name": "See Ya",
    "type": "booster",
    "atk": 0,
    "dfv": 0,
    "rez": 7,
    "effect": "Increases all Pathfinder Checks you make by +2 as long as this Program remains rezzed.",
    "cost": 20,
    "icon": "Shimmering silver magnifying glass spinning slowly in place.",
    },
    {
    "name": "Speedy Gonzalvez",
    "type": "booster",
    "atk": 0,
    "dfv": 0,
    "rez": 7,
    "effect": "Increases your Speed by +2 as long as this Program remains rezzed.",
    "cost": 100,
    "icon": "A trail of dust appearing behind the Netrunner as they move.",
    },
    {
    "name": "Worm",
    "type": "booster",
    "atk": 0,
    "dfv": 0,
    "rez": 7,
    "effect": "Increases all Backdoor Checks you make by +2 as long as this Program remains rezzed.",
    "cost": 50,
    "icon": "A golden mechanical worm with neon green eyes.",
    },
    {
    "name": "Armor",
    "type": "defender",
    "atk": 0,
    "dfv": 0,
    "rez": 7,
    "effect": "Lowers all brain damage you would receive by 4, as long as this Program remains rezzed. Only 1 copy of this Program can be running at a time. Each copy of this Program can only be used once per Netrun.",
    "cost": 50,
    "icon": "Transparent golden armor worn by the Netrunner.",
    },
    {
    "name": "Flak",
    "type": "defender",
    "atk": 0,
    "dfv": 0,
    "rez": 7,
    "effect": "Reduces the atk of all Non-Black ICE Attacker Programs run against you to 0 as long as this Program remains rezzed. Only 1 copy of this Program can be running at a time. Each copy of this Program can only be used once per Netrun.",
    "cost": 50,
    "icon": "A cloud of blinding, glowing, multi-colored lights swirling around the Netrunner.",
    },
    {
    "name": "Shield",
    "type": "defender",
    "atk": 0,
    "dfv": 0,
    "rez": 7,
    "effect": "Stops the first successful Non-Black ICE Program effect from dealing brain damage. After stopping this damage, the Shield derezzes itself. Only 1 copy of this Program can be running at a time. Each copy of this Program can only be used once per Netrun.",
    "cost": 20,
    "icon": "Flickering silver energy barrier surrounding the Netrunner.",
    },
    {
    "name": "Banhammer",
    "type": "Anti-Program Attacker",
    "atk": 1,
    "dfv": 0,
    "rez": 0,
    "effect": "Does 3d6 rez to a Non-Black ICE Program, or 2d6 rez to a Black ICE Program.",
    "cost": 50,
    "icon": "A giant glowing white sledgehammer wielded by the Netrunner.",
    },
    {
    "name": "Sword",
    "type": "Anti-Program Attacker",
    "atk": 1,
    "dfv": 0,
    "rez": 0,
    "effect": "Does 3d6 rez to a Black ICE Program, or 2d6 rez to a Non-Black ICE Program.",
    "cost": 50,
    "icon": "Glowing energy katana appearing from the Netrunner's hand.",
    },
    {
    "name": "DeckKRASH",
    "type": "Anti-Personnel Attacker",
    "atk": 0,
    "dfv": 0,
    "rez": 0,
    "effect": "Enemy Netrunner is forcibly and unsafely Jacked Out of the Architecture, suffering the effect of all rezzed enemy Black ICE they've encountered in the Architecture as they leave.",
    "cost": 100,
    "icon": "Cartoon stick of dynamite thrown by the Netrunner.",
    },
    {
    "name": "Hellbolt",
    "type": "Anti-Personnel Attacker",
    "atk": 2,
    "dfv": 0,
    "rez": 0,
    "effect": "Does 2d6 Damage direct to the enemy Netrunner's brain. Unless insulated, their Cyberdeck catches fire along with their clothing. Until they spend a Meat Action to put themselves out, they take 2 damage to their HP whenever they end their Turn. Multiple instances of this effect cannot stack.",
    "cost": 100,
    "icon": "Bolt of crimson fire launched from the Netrunner's hand.",
    },
    {
    "name": "Nervescrub",
    "type": "Anti-Personnel Attacker", 
    "atk": 0,
    "dfv": 0,
    "rez": 0,
    "effect": "Enemy Netrunner's INT, REF, and DEX are each lowered by 1d6 for the next hour (minimum 1). The effects are largely psychosomatic and leave no permanent effects.",
    "cost": 100,
    "icon": "Chrome ball thrown by the Netrunner that sparks with electricity.",
    },
    {
    "name": "Poison Flatline",
    "type": "Anti-Personnel Attacker",
    "atk": 0,
    "dfv": 0,
    "rez": 0,
    "effect": "Destroys a single Non-Black ICE Program installed on the Netrunner target's Cyberdeck at random.",
    "cost": 100,
    "icon": "Beam of neon green light shot from the Netrunner's finger.",
    },
    {
    "name": "Superglue",
    "type": "Anti-Personnel Attacker",
    "atk": 2,
    "dfv": 0,
    "rez": 0,
    "effect": "Enemy Netrunner cannot progress deeper into the Architecture or Jack Out safely for 1d6 Rounds (enemy Netrunner can still perform an unsafe Jack Out, though). Each copy of this Program can only be used once per Netrun.",
    "cost": 100,
    "icon": "A mass of sticky red goop fired from the Netrunner's hand.",
    },
    {
    "name": "Vrizzbolt",
    "type": "Anti-Personnel Attacker",
    "atk": 1,
    "dfv": 0,
    "rez": 0,
    "effect": "Damage direct to a Netrunner's brain and lowers the amount of total NET Actions the Netrunner can accomplish on their next Turn by 1 (minimum 2).",
    "cost": 50,
    "icon": "A double helix comprised of flickering neon light appearing from the Netrunner's finger.",
    }
]

hardware = [
    {
    "name": "Aerie",
    "description": "While installed, each Raven Black ICE installed on your Cyberdeck destroys a Defender Program the enemy Netrunner has Rezzed at random with their attack effect instead of derezzing it with their attack effect. ",
    "slots": 2,
    "cost": 500,
    },
    {
    "name": "Bushido Accelerator",
    "description": "For each Bushido Accelerator installed, the Speed (SPD) of all Killer Black ICE installed on your Cyberdeck increases by 2. ",
    "slots": 3,
    "cost": 500,
    },
    {
    "name": "Combat Recorder",
    "description": "While installed, whenever another netrunner fails a Death Save while jacked into the same NET Architecture as you, the Combat Recorder saves the last 5 minutes for scientific purposes, auto-scrubbing all information that might identify you. Recordings are typically worth 50eb each. Buyers don’t ask questions.",
    "slots": 1,
    "cost": 500,
    },
    {
    "name": "Defense Sequencer",
    "description": "While installed, a Defense Sequencer automatically rezzes an Armor Program installed on your Cyberdeck at the start of your next Turn without using a NET Action whenever an active Armor program is derezzed or destroyed. The Armor Program rezzed must not have been used during this Netrun.",
    "slots": 2,
    "cost": 500,
    },
    {
    "name": "Feline Instinct",
    "description": "While installed, whenever a Sabertooth Black ICE installed on your Cyberdeck destroys a program, until you Jack Out, the damage dealt by that Sabertooth increases by 1d6.",
    "slots": 2,
    "cost": 500,
    },
    {
    "name": "Hangry Hangry Dragon",
    "description": "While installed, whenever Dragon Black ICE installed on your Cyberdeck destroys a program, its Rez is restored to maximum.",
    "slots": 1,
    "cost": 500,
    },
    {
    "name": "Perfume Shoppe",
    "description": "While installed, Skunk Black ICE Programs take up 1 Program Slot in your deck instead of 2.",
    "slots": 2,
    "cost": 500,
    },
    {
    "name": "Smithy",
    "description": "While installed, as a Meat Action, you may convert all installed Sword Programs into Banhammer Programs and all installed Banhammer Programs into Sword Programs.",
    "slots": 1,
    "cost": 500,
    },
    {
    "name": "Snaketrap",
    "description": "While installed, a Snaketrap will prevent the first Black ICE or Program effect during a netrun that would destroy a Program at random on your deck. Multiple installations do nothing.",
    "slots": 1,
    "cost": 500,
    },
    {
    "name": "Swamp Mist",
    "description": "While installed, Wisp Black ICE installed on your Cyberdeck deals 2d6 damage instead of 1d6 damage. However, while installed, no Black ICE other than Wisp can be installed on your cyberdeck.",
    "slots": 2,
    "cost": 500,
    },
    {
    "name": "Swifty Clean",
    "description": "While installed, a user can perform the Cloak Interface Ability twice with a single NET Action, taking the higher outcome. However, while installed, the Cloak Interface Ability can only be used once per Netrun.",
    "slots": 2,
    "cost": 500,
    },
    {
    "name": "Backup Drive",
    "description": "While installed on a Cyberdeck, a Backup Drive 'saves' Non-Black ICE Attacker, Defender, or Booster Programs that are destroyed by pulling them into the Backup Drive the instant before they meet their end. As a Meat Action, a Netrunner can re-install all Programs 'saved' by the Backup Drive onto their deck, if they have the Slots for them. If removed from a Cyberdeck, the Backup Drive erases its contents automatically. Restored Programs with once-per-Netrun restrictions and the like are restored in the exact state they were saved in, so you can't kill your own Armor to refresh it. Yeah, that means you.",
    "slots": 2,
    "cost": 100,
    },
    {
    "name": "DNA Lock",
    "description": "A Cyberdeck with a DNA Lock can be locked and unlocked using a thumbprint, iris scan, blood sample, or any other biometric method desired. The method varies depending on the model of the DNA Lock. A locked Cyberdeck cannot be accessed without either its biometric key or a DV 17 Electronics/Security Tech Check.",
    "slots": 2,
    "cost": 100,
    },
    {
    "name": "Hardened Circuitry",
    "description": "A Cyberdeck with Hardened Circuitry cannot be rendered temporarily disabled, rendered inoperable, or destroyed by EMP effects like pulses, or Non-Black ICE Program Effects.",
    "slots": 1,
    "cost": 100,
    },
    {
    "name": "Insulated Wiring",
    "description": "A Cyberdeck with Insulated Wiring cannot catch fire or cause the user's clothing to catch fire as the result of a Program effect.",
    "slots": 1,
    "cost": 100,
    },
    {
    "name": "KRASH Barrier",
    "description": "A Cyberdeck with a KRASH Barrier is immune to any Program Effect that force the Netrunner to Jack Out, safely or unsafely. ",
    "slots": 2,
    "cost": 100,
    },
    {
    "name": "Range Upgrade",
    "description": "A Cyberdeck with a Range Upgrade can connect to an access point from up to 8m away.",
    "slots": 1,
    "cost": 100,
    }
]

black_ice = [
    {
    "name": "Asp",
    "per": 4,
    "spd": 6,
    "atk": 2,
    "dfv": 2,
    "rez": 15,
    "effect": "Destroys a single Program installed on the enemy Netrunner's cyberdeck at random.",
    "cost": 100,
    "icon": "Golden Egyptian cobra, spitting beams of neon green light.",
    },
    {
    "name": "Giant",
    "per": 2,
    "spd": 2,
    "atk": 8,
    "dfv": 4,
    "rez": 25,
    "effect": "Does 3d6 damage direct to an enemy Netrunner's brain. The Netrunner is forcibly and unsafely Jacked Out of their current Netrun. They suffer the effect of all Rezzed enemy Black ICE they've encountered in the Architecture as they leave, not including the Giant.",
    "cost": 1000,
    "icon": "A massive pair of feet and ankles towering above the enemy Netrunner.",
    },
    {
    "name": "Hellhound",
    "per": 6,
    "spd": 6,
    "atk": 6,
    "dfv": 2,
    "rez": 20,
    "effect": "Does 2d6 damage direct to the Netrunner's brain. Unless insulated, their Cyberdeck catches fire along with their clothing. Until they spend a Meat Action to put themselves out, they take 2 damage to their HP whenever they end their Turn. Multiple instances of this effect cannot stack.",
    "cost": 500,
    "icon": "A huge, black metal wolf. Its eyes glow white and fire runs in ripples all over its body. It speaks in a grating, metallic voice, repeating the enemy Netrunner's name.",
    },
    {
    "name": "Kraken",
    "per": 6,
    "spd": 2,
    "atk": 8,
    "dfv": 4,
    "rez": 30,
    "effect": "Does 3d6 damage direct to an enemy Netrunner's brain. Until the end of the Netrunner's next Turn, the Netrunner cannot progress deeper into the Architecture or Jack Out safely (The Netrunner can still perform an unsafe Jack Out).",
    "cost": 1000,
    "icon": "A mass of thrashing, orange tentacles protruding from the walls. Their suckers are covered in sticky red goop.",
    },
    {
    "name": "Liche",
    "per": 8,
    "spd": 2,
    "atk": 6,
    "dfv": 2,
    "rez": 25,
    "effect": "Enemy Netrunner's INT, REF, and DEX are each lowered by 1d6 for the next hour (minimum 1). The effects are largely psychosomatic and leave no permanent effects.",
    "cost": 500,
    "icon": "Metallic skeleton draped in black robes. Its hands are studded with blackened rings that spark with electricity",
    },
    {
    "name": "Raven",
    "per": 6,
    "spd": 4,
    "atk": 4,
    "dfv": 2,
    "rez": 15,
    "effect": "Derezzes a single Defender Program the enemy Netrunner has Rezzed at random, then deals 1d6 damage direct to the Netrunner's brain",
    "cost": 50,
    "icon": "Raven adorned in plate armor wielding a glowing white lance.",
    },
    {
    "name": "Scorpion",
    "per": 2,
    "spd": 6,
    "atk": 2,
    "dfv": 2,
    "rez": 15,
    "effect": "Enemy Netrunner's MOVE is lowered by 1d6 for the next hour (minimum 1). The effects are largely psychosomatic and leave no permanent effects.",
    "cost": 100,
    "icon": " A tiny black scorpion that hisses very loudly whenever the enemy Netrunner speaks.",
    },
    {
    "name": "Skunk",
    "per": 2,
    "spd": 4,
    "atk": 4,
    "dfv": 2,
    "rez": 10,
    "effect": "Until this Program is Derezzed, an enemy Netrunner hit by this Effect makes all Slide Checks at a -2. Each Skunk Black ICE can only affect a single Netrunner at a time, but the effects of multiple Skunks can stack.",
    "cost": 500,
    "icon": " Cartoon skunk that walks on its hind legs, following the Netrunner much too closely.",
    },
    {
    "name": "Wisp",
    "per": 4,
    "spd": 4,
    "atk": 4,
    "dfv": 2,
    "rez": 15,
    "effect": "Does 1d6 damage direct to the enemy Netrunner's brain and lowers the amount of total NET Actions the Netrunner can accomplish on their next Turn by 1 (minimum 2).",
    "cost": 50,
    "icon": "Orb of light with a single minuscule eye crackling with energy.",
    },
    {
    "name": "Dragon",
    "per": 6,
    "spd": 4,
    "atk": 6,
    "dfv": 6,
    "rez": 30,
    "effect": "Deals 6d6 damage to a Program. If this damage would be enough to Derezz the Program, it is instead Destroyed.",
    "cost": 1000,
    "icon": "Golden-scaled dragon robot wreathed in electrical discharges.",
    },
    {
    "name": "Killer",
    "per": 4,
    "spd": 8,
    "atk": 6,
    "dfv": 2,
    "rez": 20,
    "effect": "Deals 4d6 damage to a Program. If this damage would be enough to Derezz the Program, it is instead Destroyed.",
    "cost": 500,
    "icon": "Robotic samurai with red eyes wielding a glowing katana.",
    },
    {
    "name": "Sabertooth",
    "per": 8,
    "spd": 6,
    "atk": 6,
    "dfv": 2,
    "rez": 25,
    "effect": "Deals 6d6 damage to a Program. If this damage would be enough to Derezz the Program, it is instead Destroyed.",
    "cost": 1000,
    "icon": " Immense hulking cat with glowing white tusks.",
    }
]