# Generated by Django 4.2.15 on 2024-09-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0002_alter_request_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="category",
            field=models.CharField(
                choices=[
                    ("BUG", "Bug"),
                    ("BUILD", "Build"),
                    ("CGEN", "Character Generation"),
                    ("SUGGESTION", "Suggestion"),
                    ("TYPO", "Typo"),
                    ("LOGS", "Logs"),
                    ("PLOT", "Plot"),
                    ("PRP", "Player-Run Plot"),
                    ("PVP", "PvP"),
                    ("XP", "Experience Points"),
                    ("WIKI", "Wiki"),
                    ("GENERAL", "General"),
                    ("INFLUENCE", "Influence"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("OPEN", "Open"),
                    ("PENDING", "Pending"),
                    ("CLOSED", "Closed"),
                ],
                default="NEW",
                max_length=10,
            ),
        ),
    ]
