# Generated by Django 6.0.2 on 2026-03-06 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cyberpunk_sheets", "0002_initial"),
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("local", models.BooleanField(default=False)),
                ("corporate", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_language_proficiencies",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheet_language_proficiencies",
                        to="cyberpunk_sheets.charactersheet",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_language_entries",
                        to="languages.language",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("character__isnull", False),
                            ("character_sheet__isnull", False),
                            _connector="OR",
                        ),
                        name="character_language_has_character",
                    )
                ],
                "unique_together": {
                    ("character", "language"),
                    ("character_sheet", "language"),
                },
            },
        ),
    ]
