# Generated by Django 4.2.20 on 2025-05-02 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0016_character"),
        ("cyberpunk_sheets", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("local", models.BooleanField(default=False)),
                ("corporate", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_languages",
                        to="cyberpunk_sheets.charactersheet",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="languages.language",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="characterlanguage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("character__isnull", False),
                    ("character_sheet__isnull", False),
                    _connector="OR",
                ),
                name="character_language_has_character",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="characterlanguage",
            unique_together={
                ("character_sheet", "language"),
                ("character", "language"),
            },
        ),
    ]
