# Generated by Django 4.2.15 on 2024-09-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="characterlanguage",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="language",
            name="description",
        ),
        migrations.AlterField(
            model_name="characterlanguage",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name="characterlanguage",
            name="character",
        ),
    ]
