# Generated by Django 4.2.15 on 2024-09-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0004_alter_characterlanguage_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="corporate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="language",
            name="local",
            field=models.BooleanField(default=False),
        ),
    ]
