# Generated by Django 4.2.15 on 2024-10-01 23:52

from django.db import migrations

def clean_up_languages(apps, schema_editor):
    Language = apps.get_model('languages', 'Language')
    
    # Remove dictionary-like entries
    Language.objects.filter(name__startswith='{').delete()
    
    # Remove generic entries
    Language.objects.filter(name__in=['Local Language', 'Specific Language']).delete()
    
    # Update specific languages
    language_updates = {
        'English': {'local': True, 'corporate': True},
        'Streetslang': {'local': True, 'corporate': False},
        'Spanish': {'local': True, 'corporate': False},
        'Japanese': {'local': True, 'corporate': True},
        'Mandarin': {'local': True, 'corporate': True},
        'Arabic': {'local': True, 'corporate': False},
        'Hindi': {'local': True, 'corporate': True},
        'Russian': {'local': True, 'corporate': True},
        'Swahili': {'local': False, 'corporate': True},
        'Thai': {'local': True, 'corporate': False},
        'Turkish': {'local': True, 'corporate': False},
        'Farsi': {'local': True, 'corporate': False},
        'Italian': {'local': True, 'corporate': False},
    }
    
    for name, data in language_updates.items():
        Language.objects.filter(name=name).update(**data)


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0005_language_corporate_language_local"),
    ]

    operations = [
        migrations.RunPython(clean_up_languages),
    ]
