# Generated by Django 4.2.15 on 2024-09-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="affectation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="clothing_style",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="cultural_origin",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="current_hp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="current_humanity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="current_luck",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="current_state_with_your_boss",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="hairstyle",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="how_big_is_your_pack",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="how_corrupt_is_your_group",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="how_does_your_work_reach_the_public",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="how_ethical_are_you",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="how_good_bad_is_your_corp",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="how_wide_is_your_groups_jurisdiction",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="if_at_sea_what_do_they_do",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="if_in_air_what_do_they_do",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="if_on_land_what_do_they_do",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="is_your_pack_based_on_land_air_or_sea",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="life_goal",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="max_hp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="motivation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="personality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="role",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="what_division_do_you_work_in",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="what_do_you_do_for_your_pack",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="what_is_your_position_on_the_force",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="what_kind_of_corp_do_you_work_for",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="what_kind_of_fixer_are_you",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="what_kind_of_media_are_you",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="what_kind_of_medtech_are_you",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="what_kind_of_rockerboy_are_you",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="what_kind_of_runner_are_you",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="what_kind_of_solo_are_you",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="what_kind_of_tech_are_you",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="what_types_of_stories_do_you_want_to_tell",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="whats_your_moral_compass_like",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="whats_your_operational_territory",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="whats_your_packs_overall_philosophy",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="whats_your_workspace_like",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="where_do_you_get_your_programs",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="where_do_you_get_your_supplies",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="where_do_you_perform",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="where_is_your_corp_based",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="who_are_some_of_your_other_clients",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="who_are_your_main_clients",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="who_is_your_groups_major_target",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="whos_gunning_for_you",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="whos_gunning_for_you_your_group",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
