# Generated by Django 6.0.2 on 2026-03-06 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cyberpunk_sheets", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="eqarmor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_by",
                to="inventory.armor",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="eqweapon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_by",
                to="inventory.weapon",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="charactersheet",
            unique_together={("account", "character")},
        ),
    ]
