# Generated by Django 6.0.2 on 2026-03-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="notoriety",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="notoriety_points",
            field=models.IntegerField(default=0),
        ),
    ]
