# Generated by Django 4.2.15 on 2024-09-10 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cyberpunk_sheets", "0002_charactersheet_affectation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charactersheet",
            name="db_object",
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="account",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_sheet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
