# Generated by Django 4.2.15 on 2024-09-10 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cyberpunk_sheets", "0004_populate_account_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactersheet",
            name="account",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_sheet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
