# Generated by Django 4.2.15 on 2024-09-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0005_alter_charactersheet_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="death_save",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="serious_wounds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
