# Generated by Django 4.2.15 on 2024-09-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0006_charactersheet_death_save_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="charactersheet",
            old_name="current_humanity",
            new_name="humanity",
        ),
    ]
