# Generated by Django 4.2.15 on 2024-09-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0007_rename_current_humanity_charactersheet_humanity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="charactersheet",
            old_name="current_hp",
            new_name="_current_hp",
        ),
        migrations.RenameField(
            model_name="charactersheet",
            old_name="max_hp",
            new_name="_max_hp",
        ),
    ]
