# Generated by Django 4.2.15 on 2024-09-11 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0015_character_cybercharacter"),
        (
            "cyberpunk_sheets",
            "0008_rename_current_hp_charactersheet__current_hp_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="db_object",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_sheet",
                to="objects.objectdb",
            ),
        ),
    ]
