# Generated by Django 4.2.15 on 2024-09-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_link_inventory_objects_to_db"),
        ("cyberpunk_sheets", "0009_charactersheet_db_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="equipped_armor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_by",
                to="inventory.armor",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="equipped_weapon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_by",
                to="inventory.weapon",
            ),
        ),
    ]
