# Generated by Django 4.2.15 on 2024-09-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cyberpunk_sheets",
            "0013_rename_equipped_armor_charactersheet_eqarmor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="eurodollars",
            field=models.IntegerField(default=0),
        ),
    ]
