# Generated by Django 4.2.15 on 2024-09-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0015_charactersheet_rep"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="handle",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
