# Generated by Django 4.2.15 on 2024-09-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0016_charactersheet_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="reputation_points",
            field=models.IntegerField(default=0),
        ),
    ]
