# Generated by Django 4.2.15 on 2024-09-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0017_charactersheet_reputation_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="environment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="family_background",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="family_crisis",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="valued_person",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="valued_possession",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
