# Generated by Django 4.2.15 on 2024-09-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0018_charactersheet_environment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("level", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="languages",
            field=models.ManyToManyField(
                blank=True, related_name="speakers", to="cyberpunk_sheets.language"
            ),
        ),
    ]
