# Generated by Django 4.2.15 on 2024-09-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0020_remove_charactersheet_death_save_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="death_save",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="humanity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="serious_wounds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
