# Generated by Django 4.2.15 on 2024-09-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cyberpunk_sheets",
            "0021_charactersheet_death_save_charactersheet_humanity_and_more",
        ),
    ]

    operations = []
