# Generated by Django 4.2.15 on 2024-09-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0023_remove_old_language_update_charactersheet"),
    ]

    operations = []
