# Generated by Django 4.2.15 on 2024-09-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0025_auto_20240917_2107"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="humanity_loss",
            field=models.IntegerField(default=0),
        ),
    ]
