# Generated by Django 4.2.15 on 2024-09-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0026_charactersheet_humanity_loss"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
