# Generated by Django 4.2.15 on 2024-09-18 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0015_character_cybercharacter"),
        ("cyberpunk_sheets", "0027_charactersheet_is_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="character",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_character_sheet",
                to="objects.objectdb",
            ),
        ),
        migrations.AlterField(
            model_name="charactersheet",
            name="db_object",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="db_character_sheet",
                to="objects.objectdb",
            ),
        ),
    ]
