# Generated by Django 4.2.15 on 2024-09-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0028_charactersheet_character_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="total_cyberware_humanity_loss",
            field=models.IntegerField(default=0),
        ),
    ]
