# Generated by Django 4.2.15 on 2024-09-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0029_charactersheet_total_cyberware_humanity_loss"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="has_cyberarm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="unarmed_damage_dice",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="unarmed_damage_die_type",
            field=models.IntegerField(default=6),
        ),
    ]
