# Generated by Django 4.2.15 on 2024-09-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0031_add_english"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charactersheet",
            name="account",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="character",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="db_object",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="languages",
        ),
    ]
