# Generated by Django 4.2.15 on 2024-09-22 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("objects", "0016_netarchitecture_node"),
        ("cyberpunk_sheets", "0032_remove_charactersheet_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="account",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_sheet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="character",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_character_sheet",
                to="objects.objectdb",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="db_object",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="db_character_sheet",
                to="objects.objectdb",
            ),
        ),
    ]
