# Generated by Django 4.2.15 on 2024-09-22 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0016_netarchitecture_node"),
        (
            "cyberpunk_sheets",
            "0033_charactersheet_account_charactersheet_character_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactersheet",
            name="character",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_sheet",
                to="objects.objectdb",
            ),
        ),
    ]
