# Generated by Django 4.2.15 on 2024-09-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cyberpunk_sheets",
            "0035_charactersheet_anatomy_charactersheet_biology_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="hometown",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="weight",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
