# Generated by Django 4.2.15 on 2024-09-27 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cyberpunk_sheets", "0036_charactersheet_age_charactersheet_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactersheet",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_sheets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
