# Generated by Django 4.2.15 on 2024-09-27 23:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0019_chargenroom_cyberwaremerchantnpc_merchant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cyberpunk_sheets", "0038_alter_charactersheet_account"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="charactersheet",
            unique_together={("account", "character")},
        ),
    ]
