# Generated by Django 4.2.15 on 2024-10-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0005_language_corporate_language_local"),
        ("cyberpunk_sheets", "0039_alter_charactersheet_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="languages",
            field=models.ManyToManyField(
                related_name="character_sheets",
                through="languages.CharacterLanguage",
                to="languages.language",
            ),
        ),
    ]
