# Generated by Django 4.2.15 on 2024-10-07 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cyberpunk_sheets", "0041_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
