# Generated by Django 4.2.20 on 2025-05-02 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cyberpunk_sheets", "0001_initial"),
        ("cyberware", "0002_cyberwareinstance_and_more"),
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ammunition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "ammo_type",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic Ammunition"),
                            ("Armor-Piercing", "Armor-Piercing Ammunition"),
                            ("Biotoxin", "Biotoxin Ammunition"),
                            ("EMP", "EMP Ammunition"),
                            ("Expansive", "Expansive Ammunition"),
                            ("Flashbang", "Flashbang Ammunition"),
                            ("Incendiary", "Incendiary Ammunition"),
                            ("Poison", "Poison Ammunition"),
                            ("Rubber", "Rubber Ammunition"),
                            ("Sleep", "Sleep Ammunition"),
                            ("Smart", "Smart Ammunition"),
                            ("Smoke", "Smoke Ammunition"),
                            ("Teargas", "Teargas Ammunition"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("cost", models.IntegerField()),
                ("weapon_type", models.CharField(default="Generic", max_length=100)),
                ("damage_modifier", models.IntegerField(default=0)),
                ("armor_piercing", models.IntegerField(default=0)),
                (
                    "description",
                    models.CharField(default="Standard ammunition", max_length=200),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Armor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("weight", models.FloatField(default=0)),
                ("value", models.IntegerField(default=0)),
                ("sp", models.IntegerField(default=0)),
                ("ev", models.IntegerField(default=0)),
                ("locations", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cyberdeck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("hardware_slots", models.IntegerField(default=0)),
                ("program_slots", models.IntegerField(default=0)),
                ("any_slots", models.IntegerField(default=0)),
                ("value", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CyberwareInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installed", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                (
                    "character_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cyberware_objects",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cyberware_instances",
                        to="cyberpunk_sheets.charactersheet",
                    ),
                ),
                (
                    "cyberware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_app_instances",
                        to="cyberware.cyberware",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("weight", models.FloatField(default=0)),
                ("value", models.IntegerField(default=0)),
                ("category", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("weight", models.FloatField(default=0)),
                ("value", models.IntegerField(default=0)),
                ("damage", models.CharField(max_length=50)),
                ("rof", models.CharField(max_length=50)),
                ("hands", models.IntegerField(default=1)),
                ("concealable", models.BooleanField(default=False)),
                ("category", models.CharField(default="handgun", max_length=50)),
                (
                    "ammo_type",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic Ammunition"),
                            ("Armor-Piercing", "Armor-Piercing Ammunition"),
                            ("Biotoxin", "Biotoxin Ammunition"),
                            ("EMP", "EMP Ammunition"),
                            ("Expansive", "Expansive Ammunition"),
                            ("Flashbang", "Flashbang Ammunition"),
                            ("Incendiary", "Incendiary Ammunition"),
                            ("Poison", "Poison Ammunition"),
                            ("Rubber", "Rubber Ammunition"),
                            ("Sleep", "Sleep Ammunition"),
                            ("Smart", "Smart Ammunition"),
                            ("Smoke", "Smoke Ammunition"),
                            ("Teargas", "Teargas Ammunition"),
                        ],
                        default="Basic",
                        max_length=20,
                    ),
                ),
                ("current_ammo", models.PositiveIntegerField(default=0)),
                ("max_ammo", models.PositiveIntegerField(default=0)),
                ("clip", models.PositiveIntegerField(default=0)),
                ("range_dvs", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ammunition",
                    models.ManyToManyField(blank=True, to="inventory.ammunition"),
                ),
                ("armor", models.ManyToManyField(blank=True, to="inventory.armor")),
                (
                    "character",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="cyberpunk_sheets.charactersheet",
                    ),
                ),
                (
                    "character_object",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_object",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "cyberware",
                    models.ManyToManyField(
                        blank=True, to="inventory.cyberwareinstance"
                    ),
                ),
                ("gear", models.ManyToManyField(blank=True, to="inventory.gear")),
                ("weapons", models.ManyToManyField(blank=True, to="inventory.weapon")),
            ],
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("character_object__isnull", False),
                    ("character__isnull", False),
                    _connector="OR",
                ),
                name="inventory_has_character",
            ),
        ),
        migrations.AddConstraint(
            model_name="cyberwareinstance",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("character_object__isnull", False),
                    ("character_sheet__isnull", False),
                    _connector="OR",
                ),
                name="inventory_cyberware_instance_has_character",
            ),
        ),
    ]
