# Generated by Django 4.2.15 on 2024-09-10 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0015_character_cybercharacter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Armor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("weight", models.FloatField(default=0)),
                ("value", models.IntegerField(default=0)),
                ("sp", models.IntegerField()),
                ("ev", models.IntegerField(default=0)),
                ("locations", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Gear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("weight", models.FloatField(default=0)),
                ("value", models.IntegerField(default=0)),
                ("category", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("weight", models.FloatField(default=0)),
                ("value", models.IntegerField(default=0)),
                ("damage", models.CharField(max_length=30)),
                ("rof", models.CharField(max_length=30)),
                ("hands", models.IntegerField(default=1)),
                ("concealable", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("armor", models.ManyToManyField(blank=True, to="inventory.armor")),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="objects.objectdb",
                    ),
                ),
                ("gear", models.ManyToManyField(blank=True, to="inventory.gear")),
                ("weapons", models.ManyToManyField(blank=True, to="inventory.weapon")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
