# Generated by Django 5.2.8 on 2026-03-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(max_length=50)),
                ("sdp", models.PositiveIntegerField(default=35)),
                ("seats", models.PositiveIntegerField(default=2)),
                ("speed_combat", models.PositiveIntegerField(default=20)),
                ("speed_narrative", models.CharField(default="", max_length=50)),
                ("value", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="inventory",
            name="vehicles",
            field=models.ManyToManyField(blank=True, to="inventory.vehicle"),
        ),
    ]
