# Generated by Django 4.2.15 on 2024-09-10 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_sheets", "0005_alter_charactersheet_account"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="armor",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="armor",
            name="locations",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="armor",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="armor",
            name="sp",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="gear",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="gear",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="gear",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="character",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="cyberpunk_sheets.charactersheet",
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="damage",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="rof",
            field=models.CharField(max_length=50),
        ),
    ]
