# Generated by Django 6.0.2 on 2026-03-10 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_vehicle_inventory_vehicles"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeaponAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("value", models.IntegerField(default=0)),
                ("eligible_categories", models.JSONField(default=list)),
                ("requires_slot", models.BooleanField(default=False)),
                ("slot_type", models.CharField(blank=True, max_length=50)),
                ("install_dv", models.IntegerField(default=17)),
                (
                    "install_skill",
                    models.CharField(default="Weaponstech", max_length=50),
                ),
                ("effect_description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="weapon",
            name="attachment_slots",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ammunition",
            name="ammo_type",
            field=models.CharField(
                choices=[
                    ("Basic", "Basic Ammunition"),
                    ("Armor-Piercing", "Armor-Piercing Ammunition"),
                    ("Biotoxin", "Biotoxin Ammunition"),
                    ("Burrowing", "Burrowing Ammunition"),
                    ("EMP", "EMP Ammunition"),
                    ("Explosive", "Explosive Ammunition"),
                    ("Expansive", "Expansive Ammunition"),
                    ("Flashbang", "Flashbang Ammunition"),
                    ("High Precision", "High Precision Ammunition"),
                    ("High Velocity", "High Velocity Ammunition"),
                    ("Hollow Point", "Hollow Point Ammunition"),
                    ("Hyper Expansive", "Hyper Expansive Ammunition"),
                    ("Incendiary", "Incendiary Ammunition"),
                    ("Poison", "Poison Ammunition"),
                    ("Rubber", "Rubber Ammunition"),
                    ("Serrated Arrow", "Serrated Arrow Ammunition"),
                    ("Sleep", "Sleep Ammunition"),
                    ("Smart", "Smart Ammunition"),
                    ("Smoke", "Smoke Ammunition"),
                    ("Teargas", "Teargas Ammunition"),
                    ("Tracer", "Tracer Ammunition"),
                    ("Junk", "Junk Ammunition"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="ammo_type",
            field=models.CharField(
                choices=[
                    ("Basic", "Basic Ammunition"),
                    ("Armor-Piercing", "Armor-Piercing Ammunition"),
                    ("Biotoxin", "Biotoxin Ammunition"),
                    ("Burrowing", "Burrowing Ammunition"),
                    ("EMP", "EMP Ammunition"),
                    ("Explosive", "Explosive Ammunition"),
                    ("Expansive", "Expansive Ammunition"),
                    ("Flashbang", "Flashbang Ammunition"),
                    ("High Precision", "High Precision Ammunition"),
                    ("High Velocity", "High Velocity Ammunition"),
                    ("Hollow Point", "Hollow Point Ammunition"),
                    ("Hyper Expansive", "Hyper Expansive Ammunition"),
                    ("Incendiary", "Incendiary Ammunition"),
                    ("Poison", "Poison Ammunition"),
                    ("Rubber", "Rubber Ammunition"),
                    ("Serrated Arrow", "Serrated Arrow Ammunition"),
                    ("Sleep", "Sleep Ammunition"),
                    ("Smart", "Smart Ammunition"),
                    ("Smoke", "Smoke Ammunition"),
                    ("Teargas", "Teargas Ammunition"),
                    ("Tracer", "Tracer Ammunition"),
                    ("Junk", "Junk Ammunition"),
                ],
                default="Basic",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InventoryWeapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_weapons",
                        to="inventory.inventory",
                    ),
                ),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_instances",
                        to="inventory.weapon",
                    ),
                ),
                (
                    "installed_attachments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="installed_on_weapons",
                        to="inventory.weaponattachment",
                    ),
                ),
            ],
            options={
                "unique_together": {("inventory", "weapon")},
            },
        ),
        migrations.AlterField(
            model_name="inventory",
            name="weapons",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.InventoryWeapon",
                through_fields=("inventory", "weapon"),
                to="inventory.weapon",
            ),
        ),
    ]
