# Generated by Django 5.2.8 on 2026-03-10 04:46

import django.db.models.deletion
from django.db import migrations, models


def migrate_weapon_links_to_through(apps, schema_editor):
    """Copy existing inventory-weapon links to InventoryWeapon through model."""
    from django.db import connection

    InventoryWeapon = apps.get_model("inventory", "InventoryWeapon")
    with connection.cursor() as cursor:
        try:
            cursor.execute(
                "SELECT inventory_id, weapon_id FROM inventory_inventory_weapons"
            )
            rows = cursor.fetchall()
        except Exception:
            return  # Table might not exist (fresh DB) or already migrated
    for inv_id, weap_id in rows:
        InventoryWeapon.objects.get_or_create(
            inventory_id=inv_id, weapon_id=weap_id
        )


def reverse_migrate(apps, schema_editor):
    """No-op reverse; data would be in the new through table."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_vehicle_inventory_vehicles"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeaponAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("value", models.IntegerField(default=0)),
                ("eligible_categories", models.JSONField(default=list)),
                ("requires_slot", models.BooleanField(default=False)),
                ("slot_type", models.CharField(blank=True, max_length=50)),
                ("install_dv", models.IntegerField(default=17)),
                (
                    "install_skill",
                    models.CharField(default="Weaponstech", max_length=50),
                ),
                ("effect_description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="weapon",
            name="attachment_slots",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="InventoryWeapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_weapons",
                        to="inventory.inventory",
                    ),
                ),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_instances",
                        to="inventory.weapon",
                    ),
                ),
                (
                    "installed_attachments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="installed_on_weapons",
                        to="inventory.weaponattachment",
                    ),
                ),
            ],
            options={
                "unique_together": {("inventory", "weapon")},
            },
        ),
        migrations.RunPython(migrate_weapon_links_to_through, reverse_migrate),
        migrations.RemoveField(
            model_name="inventory",
            name="weapons",
        ),
        migrations.AddField(
            model_name="inventory",
            name="weapons",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.InventoryWeapon",
                through_fields=("inventory", "weapon"),
                to="inventory.weapon",
            ),
        ),
    ]
