# Generated by Django 4.2.15 on 2024-09-14 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "cyberpunk_sheets",
            "0013_rename_equipped_armor_charactersheet_eqarmor_and_more",
        ),
        ("inventory", "0003_link_inventory_objects_to_db"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cyberware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("slots", models.IntegerField(default=1)),
                ("humanity_loss", models.IntegerField(default=0)),
                ("cost", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CyberwareInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installed", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cyberware",
                        to="cyberpunk_sheets.charactersheet",
                    ),
                ),
                (
                    "cyberware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.cyberware",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="inventory",
            name="cyberware",
            field=models.ManyToManyField(blank=True, to="inventory.cyberwareinstance"),
        ),
    ]
