# Generated by Django 4.2.15 on 2024-09-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_cyberware_cyberwareinstance_inventory_cyberware"),
    ]

    operations = [
        migrations.AddField(
            model_name="weapon",
            name="category",
            field=models.CharField(default="handgun", max_length=50),
        ),
    ]
