# Generated by Django 6.0.2 on 2026-03-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_weaponattachment_weapon_attachment_slots_and_more"),
        ("inventory", "0005_alter_ammunition_ammo_type_alter_weapon_ammo_type"),
    ]

    operations = []
