# Generated by Django 4.2.15 on 2024-09-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cyberware", "0001_initial"),
        ("cyberpunk_sheets", "0025_auto_20240917_2107"),
        ("inventory", "0005_weapon_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cyberwareinstance",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cyberware_instances",
                to="cyberpunk_sheets.charactersheet",
            ),
        ),
        migrations.AlterField(
            model_name="cyberwareinstance",
            name="cyberware",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cyberware.cyberware"
            ),
        ),
        migrations.DeleteModel(
            name="Cyberware",
        ),
    ]
