# Generated by Django 4.2.15 on 2024-09-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_cyberwareinstance_character_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyberwareinstance",
            name="is_cyberdeck",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gear",
            name="is_cyberdeck",
            field=models.BooleanField(default=False),
        ),
    ]
