# Generated by Django 4.2.15 on 2024-09-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_cyberwareinstance_is_cyberdeck_gear_is_cyberdeck"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cyberwareinstance",
            name="is_cyberdeck",
        ),
        migrations.RemoveField(
            model_name="gear",
            name="is_cyberdeck",
        ),
    ]
