# Generated by Django 4.2.15 on 2024-09-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_remove_cyberwareinstance_is_cyberdeck_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyberwareinstance",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
