# Generated by Django 4.2.15 on 2024-09-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_cyberwareinstance_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ammunition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "ammo_type",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic Ammunition"),
                            ("Armor-Piercing", "Armor-Piercing Ammunition"),
                            ("Biotoxin", "Biotoxin Ammunition"),
                            ("EMP", "EMP Ammunition"),
                            ("Expansive", "Expansive Ammunition"),
                            ("Flashbang", "Flashbang Ammunition"),
                            ("Incendiary", "Incendiary Ammunition"),
                            ("Poison", "Poison Ammunition"),
                            ("Rubber", "Rubber Ammunition"),
                            ("Sleep", "Sleep Ammunition"),
                            ("Smart", "Smart Ammunition"),
                            ("Smoke", "Smoke Ammunition"),
                            ("Teargas", "Teargas Ammunition"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("cost", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="weapon",
            name="ammo_type",
            field=models.CharField(
                choices=[
                    ("Basic", "Basic Ammunition"),
                    ("Armor-Piercing", "Armor-Piercing Ammunition"),
                    ("Biotoxin", "Biotoxin Ammunition"),
                    ("EMP", "EMP Ammunition"),
                    ("Expansive", "Expansive Ammunition"),
                    ("Flashbang", "Flashbang Ammunition"),
                    ("Incendiary", "Incendiary Ammunition"),
                    ("Poison", "Poison Ammunition"),
                    ("Rubber", "Rubber Ammunition"),
                    ("Sleep", "Sleep Ammunition"),
                    ("Smart", "Smart Ammunition"),
                    ("Smoke", "Smoke Ammunition"),
                    ("Teargas", "Teargas Ammunition"),
                ],
                default="Basic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="current_ammo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weapon",
            name="max_ammo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventory",
            name="ammunition",
            field=models.ManyToManyField(blank=True, to="inventory.ammunition"),
        ),
    ]
