# Generated by Django 4.2.15 on 2024-09-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_weapon_clip"),
    ]

    operations = [
        migrations.AddField(
            model_name="weapon",
            name="range_dvs",
            field=models.JSONField(default=dict),
        ),
    ]
