# Generated by Django 4.2.15 on 2024-09-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_weapon_range_dvs"),
    ]

    operations = [
        migrations.AddField(
            model_name="ammunition",
            name="armor_piercing",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ammunition",
            name="damage_modifier",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ammunition",
            name="description",
            field=models.CharField(default="Standard ammunition", max_length=200),
        ),
        migrations.AddField(
            model_name="ammunition",
            name="weapon_type",
            field=models.CharField(default="Generic", max_length=100),
        ),
    ]
