# Generated by Django 4.2.15 on 2024-09-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0013_ammunition_armor_piercing_ammunition_damage_modifier_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Cyberdeck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("hardware_slots", models.IntegerField(default=0)),
                ("program_slots", models.IntegerField(default=0)),
                ("any_slots", models.IntegerField(default=0)),
                ("value", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
