# Generated by Django 4.2.15 on 2024-10-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_cyberdeck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ammunition",
            name="ammo_type",
            field=models.CharField(choices=[], max_length=20),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="ammo_type",
            field=models.CharField(choices=[], default="", max_length=20),
        ),
    ]
